### ISSUE TITLE
Issue with background scripts

### ISSUE THREAD

**Issue by sumsalabim** [Jonghakseo/chrome-extension-boilerplate-react-vite#109]
Hey, I'm having one issue with background scripts (screen)
![image](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/37812273/ed7193cd-73b4-4f11-91a6-e79f1e7fed21)

I want to check if SPA url is changed, to push message to my content scripts, because I'm getting data from storage on website, but after clicking other page and coming back, this data is no longer replaced

I'm adding many different listeners to background scripts, but it seems that noone of them is working, so I assume it's connected to problem from screenshot

Any idea how I could fix that issue?

**Comment by Jonghakseo** [comment]
Please check if the web socket server on the local server is working properly. It should be run with the command `yarn dev`.

**Comment by sumsalabim** [comment]
Here is the output from yarn dev, everything seems to be working fine, but there is still a problem with connection to WebSocket. I can't find an answer for that and only possibility for me to work on this template is to turn off all the autoupdates, and refresh package manually.. 

`╰─ yarn dev
yarn run v1.22.17
$ npm run build:hmr && (run-p wss build:watch)

> of-replacer@0.0.1 build:hmr
> rollup --config utils/reload/rollup.config.ts


utils/reload/initReloadServer.ts → utils/reload/initReloadServer.js...
created utils/reload/initReloadServer.js in 1.4s

utils/reload/injections/script.ts → utils/reload/injections/script.js...
created utils/reload/injections/script.js in 9ms

utils/reload/injections/view.ts → utils/reload/injections/view.js...
created utils/reload/injections/view.js in 7ms
$ node utils/reload/initReloadServer.js
$ cross-env __DEV__=true vite build --watch
[HRS] Server listening at ws://localhost:8081
vite v3.1.3 building for production...

watching for file changes...

build started...
 Manifest file copy complete: /Users/kacper.sitarz/Projects/of-replacer-final/dist/manifest.json
✓ 48 modules transformed.
dist/src/pages/panel/index.html                       0.48 KiB
dist/src/pages/devtools/index.html                    0.29 KiB
dist/src/pages/popup/index.html                       0.47 KiB
dist/src/pages/devtools/index.js                      0.20 KiB
dist/src/pages/panel/index.js                         0.67 KiB
dist/src/pages/content/index.js                       1.17 KiB
dist/src/pages/background/index.js                    1.88 KiB
dist/src/pages/popup/index.js                         3.12 KiB
dist/assets/js/modulepreload-polyfill.js              1.27 KiB
dist/assets/js/_virtual_reload-on-update-in-view.js   217.66 KiB
dist/assets/js/index.js                               1.66 KiB
dist/assets/css/panelIndex.chunk.css                  0.07 KiB
dist/assets/css/contentStyle16849193296.chunk.css     0.07 KiB
dist/assets/css/popupIndex.chunk.css                  1.30 KiB
built in 640ms.
`

**Comment by sumsalabim** [comment]
Okay it seems that this error is not occuring while I'm building for production. But starting project with yarn dev is causing this issue. Is there any way i can use HMR but still build to PROD, so websockets will be working fine?

**Comment by Jonghakseo** [comment]
PROD builds don't have this problem because they don't run the websocket server.

Are you using a non-Chromium browser by any chance?
