### ISSUE TITLE
why use vite

### ISSUE THREAD

**Issue by JunyWuuuu91** [Jonghakseo/chrome-extension-boilerplate-react-vite#11]
in dev mode, the vite not  as fast as expected。install crx also use full static resources, so vite must build every time。

have any better case to make speed faster?

**Comment by Jonghakseo** [comment]
Hi @JunyWuuuu91 
hmm... I will think about how to provide crx through the dev server.

**Comment by JunyWuuuu91** [comment]
> Hi @JunyWuuuu91 hmm... I will think about how to provide crx through the dev server.
@Jonghakseo 
thanks, forward to your results
