### ISSUE TITLE
How would you add tailwinds to this repo? 

### ISSUE THREAD

**Issue by remusris** [Jonghakseo/chrome-extension-boilerplate-react-vite#113]
Any recommendations on how to add tailwinds to this repo?

**Comment by Jonghakseo** [comment]
Okay. Although I'm not a big fan of Tailwind, I understand that many people find it useful. I'll give it a try.

**Comment by Jonghakseo** [comment]
To my friends who have been waiting for this... I apologize for the delay due to personal circumstances. I will be working on this starting this week.

**Comment by Jonghakseo** [comment]
- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/138

**Comment by Jonghakseo** [comment]
@all-contributors please add @remusris for ideas
