### ISSUE TITLE
Question about the new tab feature

### ISSUE THREAD

**Issue by LucaCuello** [Jonghakseo/chrome-extension-boilerplate-react-vite#114]
Hi! I've discovered this template just now. Been testing it and I love it so far! It's sooooo helpful. 
I have a noobie question tho, what's the point of the new tab feature? I want to build an extension but I don't want the extension itself to replace the content of the new tab when a users installs it. Is there a way to disable this?

**Comment by Jonghakseo** [comment]
Remove the new tab from the manifest and remove all components of the new tab folder. It's that simple.

delete below codes

### manifest.ts L:20~22

```ts
chrome_url_overrides: {
    newtab: "src/pages/newtab/index.html",
  },
```

### vite.config.ts L:53
```ts
        newtab: resolve(pagesDir, "newtab", "index.html"),
```

And re-install extension!

**Comment by LucaCuello** [comment]
Damn, I'm feeling so dumb rn lol
Thank you!
