### ISSUE TITLE
styles not working for content 

### ISSUE THREAD

**Issue by spencerc99** [Jonghakseo/chrome-extension-boilerplate-react-vite#12]
Could you show an example of how to get styles working with content rendered in `contentView`? I've tried importing scss/css files in the react typescript files but they don't seem to be getting loaded. I also tried to mimic your runtime bundling by manually inserting a `link` tag to the public `contentStyle.css` file generated, but that did't work either

**Comment by JunyWuuuu91** [comment]
im my case, i create a single `style.scss` file in `content` folder, 
```css
@import "./styles/xxxx.scss";
@include echo;
// ....
```

then configure it in `vite.config.ts`
```ts
 rollupOptions: {
      input: {
        // ....
        contentStyle: resolve(pagesDir, "content", "style.scss"),
      },
      output: {
        assetFileNames: "assets/[ext]/[name].chunk.[ext]",
      }
    },
```

finally, update `manifest.ts`

```ts 
content_scripts: [ { css: assets/css/contentStyle.css, /*...*/ } ]
web_accessible_resources: [ { resources: [ "assets/css/*.css", /*...*/ ] } ]
```

of cource , u can set css by chrome API
```js
chrome.scripting.insertCSS({
          files: ["assets/css/contentStyle.chunk.css"],
          target: {
            tabId,
          },
        })
```

**Comment by spencerc99** [comment]
awesome thank you! I got it working by manually compiling into `contentStyle.css` but wanted to make better use of vite, which this seems to take full advantage of. I'll try this out

**Comment by Jonghakseo** [comment]
maybe this will help
- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/16

**Comment by Jonghakseo** [comment]
@all-contributors please add @spencerc99 for bug
