### ISSUE TITLE
How cloud i import images from assets dir？

### ISSUE THREAD

**Issue by zhanglong12138** [Jonghakseo/chrome-extension-boilerplate-react-vite#123]
I inject a modal compoent into pages by content script.After build package and load extension.The image address is link to tabpage's URL instead of extension resources.How to import images in common according to content scrit
```
import { useState } from 'react'
import logo from '@assets/img/logo.png'

function App() {
  const [modalShow, setModalShow] = useState(false)
  const [modalShowAlways, setModalShowAlways] = useState(false)
  const onMouseOver = () => {
    if (modalShow) return
    setModalShow(true)
  }
  const onMouseLeave = () => {
    if (!modalShow) return
    setModalShow(false)
  }

  return (
    <div className="tl-helper-chrome-extension-frame">
      <div className="tip">
        <img src={logo} />
      </div>
      <div className={`tl-container ${(modalShowAlways || modalShow) ? 'modalShow' : ''}`} onMouseOver={onMouseOver} onMouseLeave={onMouseLeave}>
        <div className="w100 fl fc">
          <div className="tl-header fl fr">
            <img className="tl-header-logo f1" src={logo} />
            <div className="tl-header-title f1">xx hepler</div>
            <div className="tl-header-close" onClick={() => setModalShowAlways(false)}>×</div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default App
```
Render result:
![image](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/20243414/c5153d18-0ff9-4ed1-88a2-2d4d3957734f)

when i open it,i find it links to tabpage's url like "https://xxxx.com/assets/png/imgLogo.chunk.png" but not "chrome-extension://bhlhnicpbhignbdhedgjhgdocnmhomnp/html/assets/png/imgLogo.chunk.png"

**Comment by zhanglong12138** [comment]
I try to import image resources as popup page of demo,but it didn't work.I think it's different from content script inject components.

**Comment by Hoony0321** [comment]
There is a same issue.
[https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/38](url)

i had a same problem. but it's working now by referring to the closed issue

**Comment by zhanglong12138** [comment]
> There is a same issue. [https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/38](url)
> 
> i had a same problem. but it's working now by referring to the closed issue

I can not open it, do you have somethings with static resources importing.I try to do it with vite.config.ts but not success yet.

**Comment by Jonghakseo** [comment]
https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/38
