### ISSUE TITLE
How to Inject script from content_script

### ISSUE THREAD

**Issue by maitrungduc1410** [Jonghakseo/chrome-extension-boilerplate-react-vite#124]
A common case when building an extension is that from content_script, we inject some JS code to get some infor, send back to content_script.

Detail: from content_script, we inject a file named `custom_script.js` (or .ts) to the host page

But with this project setup, I don't know how to preserve `custom_script.js` during compilation. Because from what I see, it's not in the `dist` output folder

**Comment by Jonghakseo** [comment]
This is a boilerplate that somewhat abstracts the typical extension building process to make it easier for first-time extension builders.

The use case you describe is a rather low-level behavior, so you may need to touch some customizations.

First, you'll need to manually modify your `manifest.ts` file to fix the current structure, which uses a single content script file in the manifest.

```ts
content_scripts: [
    {
      matches: ["http://*/*", "https://*/*", "<all_urls>"],
      js: ["src/pages/content/index.js", "js/content/example.js"],
      css: ["assets/css/contentStyle.chunk.css"],
    },
  ],
```

Then, if you create a `js/content/example.js` file inside the public folder and build it, you should be able to successfully load the example.js file from the content script.

<img width="271" alt="스크린샷 2023-06-23 오후 3 14 10" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/53500778/7f9bba34-60fd-4a00-94af-023a7eda5c0e">

**Comment by maitrungduc1410** [comment]
hi thanks for your response, I modified `vite.config.js` add the injected script to `input` and achieved what I want

**Comment by Jonghakseo** [comment]
I apologize for the late response. Glad to hear the issue was resolved :)

I'll close this issue.
