### ISSUE TITLE
Safari support?

### ISSUE THREAD

**Issue by leolorenzoluis** [Jonghakseo/chrome-extension-boilerplate-react-vite#128]
Is it possible to extend this to safari and other browsers? As of now it’s chrome

**Comment by Jonghakseo** [comment]
well... as far as I know, Chrome browser extensions only work on Chromium browsers (e.g. Naver Whale or something). If you want to build Safari web extensions, please refer to this link. When I saw that document, the structure seemed so similar to Chrome extensions.

https://developer.apple.com/documentation/safariservices/safari_web_extensions/creating_a_safari_web_extension

**Comment by Lukasvo** [comment]
FYI You can easily convert your Chrome extension to a Safari extension using the command `xcrun safari-web-extension-converter ./dist`. Xcode should be installed. (I'm on Mac).

See https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari
