### ISSUE TITLE
code in contentView can't call functions on `chrome.runtime` without specifying extension id

### ISSUE THREAD

**Issue by spencerc99** [Jonghakseo/chrome-extension-boilerplate-react-vite#13]
Wondering the reason behind you injecting the `contentView` script in the `content` `index.ts` rather than just directly rendering everything in the `content` script? Running into a small issue where I have to manually pass the chrome extension ID in order to run any of the chrome scripts which is just a bit annoying

**Comment by Jonghakseo** [comment]
Hello @spencerc99 
You may find this PR helpful.
- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/9

**Comment by bowencool** [comment]
use `import("src/pages/contentView/index.js")` instead

**Comment by spencerc99** [comment]
It seems to be something with appropriate loading because using it inside `useEffect` does seem to work. Any ideas?

**Comment by Jonghakseo** [comment]
@spencerc99 

The part causing the error has been removed from the source code. Would you like to clear the cache and check again?
