### ISSUE TITLE
How to auto reload chrome extension?

### ISSUE THREAD

**Issue by twicer-is-coder** [Jonghakseo/chrome-extension-boilerplate-react-vite#131]
The problem is it automatically refreshes the page but does not reload the extension auto. I have to go to manually click refresh in chrome://extensions.

**Comment by Jonghakseo** [comment]
Modifications to frontend units, such as content scripts, are mostly updated on refresh.

A common case where a reload is required to reflect changes in an extension is inside a background script. 

However, if you want to reload the extension for a specific change, insert the following code where you want it to detect the change.

```ts
import reloadOnUpdate from "virtual:reload-on-update-in-background-script";

reloadOnUpdate("pages/someWhere");
```

**Comment by hoathai** [comment]
Is there a way to deploy the newtab page to a webserver as a webapp?

**Comment by Jonghakseo** [comment]
Perhaps an iframe...? But I'm not sure if that's allowed by policy. There's nothing wrong with having a separate server for the data and rendering it in a new tab.

Take a look at my favorite, [daily.dev](https://daily.dev/)!

**Comment by Jonghakseo** [comment]
Close it for issue management. Anyone can reopen it for similar or identical issue raising.
