### ISSUE TITLE
How to set NODE_ENV to development ?

### ISSUE THREAD

**Issue by stevebeauge** [Jonghakseo/chrome-extension-boilerplate-react-vite#133]
I'm building a chrome extension in which I use some packages that have custom dev tools (react-query to be named).

The devtools, as [stated in the documentation](https://tanstack.com/query/latest/docs/react/devtools#install-and-import-the-devtools), is bundled only when `NODE_ENV `is set to `development`.

When I `pnpm run dev`, I don't have the var properly set.

To check what is the value of this node env variable, I added a `console.log("env", process.env);` directly inside `vite.config.ts` file.

I can see when starting the dev script: `NODE_ENV: 'production'`.

How to ensure this env variable is properly set ?

I tried to fix all the package.json to force the value, without success:

````json
  "scripts": {
    "build": "tsc --noEmit && vite build",
    "build:watch": "cross-env __DEV__=true NODE_ENV=development vite build --watch",
    "build:hmr": "cross-env NODE_ENV=development rollup --config utils/reload/rollup.config.ts --configPlugin typescript",
    "wss": "cross-env NODE_ENV=development node utils/reload/initReloadServer.js",
    "dev": "cross-env NODE_ENV=development pnpm run build:hmr && (run-p wss build:watch)",
    "test": "jest"
  },
````

Thanks

**Comment by Jonghakseo** [comment]
`process.env.NODE_ENV = "development";` in `vite.config.ts` is not working?

**Comment by stevebeauge** [comment]
Seems to work ! 
Thanks !
