### ISSUE TITLE
HMR wanted

### ISSUE THREAD

**Issue by bowencool** [Jonghakseo/chrome-extension-boilerplate-react-vite#14]

**Comment by Jonghakseo** [comment]
Thank you. Currently trying to solve with this issue(https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/11)

**Comment by monokaijs** [comment]
Any update about this?

**Comment by Jonghakseo** [comment]
> Any update about this?

I tried to provide the files of the dev server locally, but it didn't work, so I'm looking for another way.

**Comment by Jonghakseo** [comment]
As a workaround, I created a PR that uses websockets to trigger a refresh whenever dist changes. I would appreciate it if you could send me a comment after checking it out.

https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/25
