### ISSUE TITLE
How can I make it work better under chrome i18n?

### ISSUE THREAD

**Issue by hegelwatch** [Jonghakseo/chrome-extension-boilerplate-react-vite#140]
Hey,

I've been developing a Chrome Extension using this Boilerplate and have made some good progress. It's been really helpful, thank you.

Now, I'd like to implement internationalization in my Chrome Extension using chrome.i18n. To add the _locales directory under the plugin root directory, I created a _locales directory under the public directory in this Boilerplate and set up multiple language files according to Google's documentation. I was successful in displaying content in different languages correctly in the plugin. However, I encountered an issue: by default, the public directory does not watched for changes under hot module replacement (HMR).

I attempted to add "public/_locales/**" to build.rollupOptions.watch.include in vite.config.ts, but this didn't work. Is there a way to have the template monitor my public/_locales directory? Or is there another way for me to set up _locales under the plugin root directory so that it works better with HMR?

Thank you very much for your help.

**Comment by Jonghakseo** [comment]
I can think of a few hacky ways to do it, but I'll have to think about how to do it in a way that's comfortable and elegant.

Personally, I did it manually... reloading the locale as I was finalizing it :(

**Comment by hegelwatch** [comment]
> 

Thank you for response. So, is it possible to add this requirement to the feature request and include it in the HRR functionality of this Boilerplate? Because chrome i18n is also a common development requirement for Chrome plugins. However, I really hope that I can achieve HRR for the files in the _locales directory locally after configuration. I can't do it myself now. It significantly impacts development efficiency to work with this Boilerplate for multilingual because it doesn't support HRR and the plugin doesn't update automatically. Every time I finish configuring the messages.json file, I have to uninstall and reinstall the plugin for changes to take effect.

**Comment by Jonghakseo** [comment]
I didn't realize the need for i18n until relatively late in my personal work. I'll try to add that to the boilerplate. :)

**Comment by hegelwatch** [comment]
Thank you, I'm looking forward to it

**Comment by Jonghakseo** [comment]
@hegelwatch 

- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/145

I'm not sure if HRR is good for the developer experience, as adding i18n always requires a rebuild + reload.
Anyway, I've added the desired functionality, so please check it out.

+@ There are also a couple of fixes I made to the main branch before doing this.

**Comment by hegelwatch** [comment]
Hi, thanks for offering the i18n HRR feature. I've spent some time integrating it into my own project recently.

In my view, the development experience for i18n HRR is not an issue, since it's an optional feature rather than a mandatory one. If I need the i18n function, then I indeed require HRR, this is exactly what I need. If the rebuild + reload process is troublesome, I think it could be mentioned in the introduction to keep developers informed. It won't interfere with developers who don't use i18n.

Additionally, the current i18n method, which automatically loads all keys from message.json as TypeScript types and provides code prompts, is amazing. It's a great implementation, and I absolutely love it!

However, there's still a problem. Currently, it only supports HRR for the English language and not for others. Even if I configure the default_locale in the manifest to another language, like zh_CN, it only produces effects for en. The HRR and i18n method's type processing for other languages is ineffective. I see this as an issue. HRR should apply to all message.json files under _locales to support all languages, not just English. Developers might work in various languages, like myself. It should at least be effective for the language specified by the default_locale in the manifest.

Moreover, I think a better design idea is that _locales doesn't necessarily have to be in public. Perhaps it could have its own directory like pages. It might be easier for you to handle it this way. It should be designed as a templated optional feature, just like other pages provided. I'm not sure if this might enable faster compilation like other pages, and this might be something for you to consider.

Thanks for taking the time to consider solving these issues. My plugin development is nearing completion, and I look forward to seeing this template develop further.
(This content has been translated by GPT-4. Please excuse any language inaccuracies or impoliteness.)

**Comment by Jonghakseo** [comment]
@hegelwatch 

For cases where we need to support more than one language, I think we can make it possible to implement without knowing the specifics of each language. I'll edit the PR to take this into account.

I agree with you about hiding _locales, but I have a concern. I'm concerned that Chrome extension frameworks, including Plasmo, implement overly abstract layers that make it too difficult to understand how Chrome extensions work.

From a usability standpoint, that might be better, but it's a concern. Thanks for the suggestion.

(I'm using a translator too, lol)

**Comment by hegelwatch** [comment]
@Jonghakseo 

The idea about supporting multiple languages sounds fantastic, and I'm looking forward to its implementation.

Regarding _locales, my thought isn't about hiding _locales but rather putting it at the root level, alongside pages, and maintaining the _locales directory structure the same as that in Chrome extension frameworks, just not under public. If developers need i18n, they can create a _locales at the root directory and use it just like they would in Chrome extension frameworks to create language directories. Then this directory could automatically apply HRR. This might feel more natural than placing it under Public. But I'm not sure if this change is significantly different from keeping it under public, or whether it can achieve faster compilation like other pages do.

But in the end, this decision depends on your design. The current approach is also good. I'm looking forward to the updates.

**Comment by hegelwatch** [comment]
I'm not sure why, but after using the new project, everything was initially normal. However, after working for a while, now when changes to the message.json content trigger HRR, the Chrome extension doesn't automatically read the latest message.json content. I still need to manually reload the plugin to access the latest message.json content. I'm not sure why this is happening.

**Comment by Jonghakseo** [comment]
@hegelwatch
Ok. I will check it too.

**Comment by hegelwatch** [comment]
@Jonghakseo 

Hello, I'm not sure what I did, but as far as I remember, I didn't do anything except the regular debugging of the code. But suddenly, under the npm run dev mode, the background.js failed to load. The error is as follows:
Service worker registration failed. Status code: 15
Uncaught ReferenceError: document is not defined

Context:
assets/js/_virtual_reload-on-update-in-view.js
Stack trace:
}
function reloadWhenTabIsVisible() {
!document.hidden && pendingReload && reload();
}
document.addEventListener("visibilitychange", reloadWhenTabIsVisible); // This line is marked as a yellow error line by the Chrome debugger
}
export {
addHmrIntoView as a
};

This seems to be some sort of issue with HRR, and I didn't change the background.ts code (it's been running smoothly and the codebase is small). But I'm really at a loss now. I'm stuck here, so I hope you can provide some solutions as soon as possible, otherwise my work will be stalled. Thank you very much.

**Comment by Jonghakseo** [comment]
@hegelwatch 

Thank you for attaching a detailed error log.

The problem seems to be with the client-side refresh called by `import refreshOnUpdate from "virtual:reload-on-update-in-view";`.

Could you try nullable processing on the document, window objects inside the `utils/reload/injections/view.ts` file? Please modify the code as below and run `npm run dev` once again.

If it doesn't work, please get back to me.
```ts
import initReloadClient from "../initReloadClient";

export default function addHmrIntoView(watchPath: string) {
  let pendingReload = false;

  initReloadClient({
    watchPath,
    onUpdate: () => {
      // disable reload when tab is hidden
      if (document?.hidden) {
        pendingReload = true;
        return;
      }
      reload();
    },
  });

  // reload
  function reload(): void {
    pendingReload = false;
    window?.location.reload();
  }

  // reload when tab is visible
  function reloadWhenTabIsVisible(): void {
    !document?.hidden && pendingReload && reload();
  }
  document?.addEventListener("visibilitychange", reloadWhenTabIsVisible);
}

```

**Comment by hegelwatch** [comment]
@Jonghakseo 

I tried to modify the code as follows:

```typescript
// reload when tab is visible
function reloadWhenTabIsVisible() {
  if (document) {
    !document.hidden && pendingReload && reload();
  }
}
if (document) {
  document.addEventListener("visibilitychange", reloadWhenTabIsVisible);
}

``` 
However, it didn't work. Then I attempted to change the code again:

```typescript
// reload when tab is visible
function reloadWhenTabIsVisible() {
  if (document) {
    !(document?.hidden) && pendingReload && reload();
  }
}
if (document) {
  document?.addEventListener("visibilitychange", reloadWhenTabIsVisible);
}
``` 
But I still encountered an error:

```
Service worker registration failed. Status code: 15
Uncaught ReferenceError: document is not defined
function reloadWhenTabIsVisible() {
  if (document) {
    !(document == null ? void 0 : document.hidden) && pendingReload && reload();
  }
}
if (document) { // This line is marked as a yellow error by the Chrome debugger
  document == null ? void 0 : document.addEventListener("visibilitychange", reloadWhenTabIsVisible);
}
``` 
I find this situation quite perplexing. Why did it work fine before and suddenly start causing this issue, which is difficult to resolve?

**Comment by Jonghakseo** [comment]
@hegelwatch 

Okay. I get it. 

Are you calling "refreshOnUpdate" from a background service worker or from a function that depends on it?

In a non-browser environment like a node, you'll get the following error when referencing the document. And the part about the service worker registration failing also refers to that.

**Comment by Jonghakseo** [comment]
Are you calling the i18n multilingual function in the background by any chance, this could be an issue as the i18n function is using refreshOnUpdate.

**Comment by Jonghakseo** [comment]
> @Jonghakseo
> 
> Oh, I see. Although I'm not directly using i18n in background.ts, I have imported config.ts in background.ts, and config.ts uses i18n. Even though the modules I import in background.ts don't use i18n directly, when I remove the import of config.ts, the background script works fine. So, the issue was caused by this. Is there a way to import config.ts in background.ts while still using i18n in config.ts and ensuring that the background script works correctly?


fix `i18n.ts`

```ts
import type EnMessage from "public/_locales/en/messages.json";
import refreshOnUpdate from "virtual:reload-on-update-in-view";

type Keys = keyof typeof EnMessage;

// In non-browser environments, the window object is undefined.
typeof window !== "undefined" &&
  refreshOnUpdate("public/_locales/en/messages.json");

export function i18n(key: Keys) {
  return chrome.i18n.getMessage(key);
}

```

**Comment by Jonghakseo** [comment]
We've added support for all languages as a [commit](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/145/commits/67a90af695d00b09d877a789fee28dc1d93c9e77) to this [PR](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/145). Let's check out the behavior, please?

**Comment by hegelwatch** [comment]
Hey, I apologize for the late reply; I've been quite busy these past few days.

I've updated my project to the latest commit, and now everything with background.js is normal. However, there are still some serious issues in my opinion:

1.Now, any language can perform HRR, which is great, but after HRR, the latest changes to the message.js content are not reflected on the page. I still need to reload the plugin manually.
2.The default language now seems to have switched from English to Korean, and TypeScript type checking can only recognize from Korean (ko/message.js); it does not work for other languages. This forces me to switch my Chrome's language to Korean to work. If I add a key in the message.js of any other language, it can't be recognized in the i18n function in the project. Ideally, any key added to the message.js under any language should be recognized by TypeScript types in the i18n function. If this is not achievable, at least it should allow me to work under the default language set in the default_locale in manifest.ts (this is also the method in the official documentation).
Thank you for taking the time to fix these issues. I hope these current issues can be resolved too. Thanks.

**Comment by hegelwatch** [comment]
I need to add something. After multiple tests, I found that my description in the second step above was not complete. Now, TypeScript's type checking does not only apply to Korean (ko/message.js) but requires the key to be written in both Korean (ko/message.js) and English (en/message.js) to take effect. If either of these two files is missing the key, it won't work. Meanwhile, adding a key in my default directory zh_CN/message.js doesn't work at all.

Even so, there are still some issues. I believe that this TypeScript type checking should be based on the default_locale in manifest.ts to be more reasonable.

**Comment by Jonghakseo** [comment]
@all-contributors please add @hegelwatch for ideas
