### ISSUE TITLE
How to detect when my DevTools panel is open?

### ISSUE THREAD

**Issue by lucgagan** [Jonghakseo/chrome-extension-boilerplate-react-vite#144]
I cannot find documentation. Trying my luck here!

**Comment by Jonghakseo** [comment]
## 1. Open the Chrome Devtools And Find "Dev Tools" (it's written in `src/pages/devtools/index.ts`)

<img width="528" alt="스크린샷 2023-07-01 오후 10 22 51" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/53500778/94ec4b27-ad8c-4bd9-b40b-f573c7c2b19f">

## 2. Enjoy

<img width="530" alt="스크린샷 2023-07-01 오후 10 22 56" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/53500778/3f9c7c91-e439-41f4-9bf0-577889b8d1a7">

**Comment by Jonghakseo** [comment]
Close for issue management. Anyone can reopen it for similar or identical issue raising.
