### ISSUE TITLE
Built code can be hard to read for Chrome Store reviewer.

### ISSUE THREAD

**Issue by 1g0rrr** [Jonghakseo/chrome-extension-boilerplate-react-vite#156]
Documentation from Chrome Store said:

> Amount and formatting of code
> The more code an extension contains, the more work it takes to verify that code is safe. Obfuscation is disallowed as it increases the complexity of the validation process. Minification is allowed, but it can also make reviewing extension code more difficult. Where possible, consider submitting your code as authored. You may also want to consider structuring your code in a way that is easy for others to understand.

https://developer.chrome.com/docs/webstore/review-process/

But Vite makes code quite hard to read after build.
Did anyone hear about problems with publishing extensions after building with Vite? 
How to make code as easy as possible to read after building?

**Comment by Jonghakseo** [comment]
@1g0rrr 

hello. I was concerned about this at one point, but I personally have never had code built via boilerplate rejected for being hard to read.

Even as my projects have grown in size and the amount of obfuscated code has increased, the "readability" of my code has never been an issue.

If I had to guess, I'd say that Google internally also uses automated tests to review extension-sensitive code.

**Comment by 1g0rrr** [comment]
Ok, thanks for the answer! My app is in the review process, so we'll see how it ends up
