### ISSUE TITLE
TypeError: Failed to fetch dynamically imported module

### ISSUE THREAD

**Issue by chrisozgo99** [Jonghakseo/chrome-extension-boilerplate-react-vite#157]
I'm getting the following error when trying to inject some HTML via this chrome extension boilerplate:

```Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: chrome-extension://{my-extension-id}/assets/js/index.js```

It only happens about 10% of the time, which is strange. I think it has something to do with the Vite configuration, although, it is difficult to debug with it only happening occasionally.

Might it have something to do with the customDynamicImport() function, or some other custom configuration of this boilerplate? Any help would be appreciated!

**Comment by Jonghakseo** [comment]
Can you give me a little more information on what you mean by injecting some HTML?

**Comment by chrisozgo99** [comment]
As additional context, it seems like the only time this happens is upon making a file change. The webpage reloads automatically and executes the rollup (via the ```npm run dev``` script, but then if you don't reload the extension in the `chrome://extensions/` webpage, it throws that error.

So I'm guessing this would not affect anything in production because there won't be any changes to the files, but it serves as a minor inconvenience in development.

I'm new to Vite and Chrome Extensions though, so if there is anything above that doesn't add up or make sense, please help me to understand.

**Comment by lwh795** [comment]
I encountered the same problem on my vite project，has this problem been solved？

**Comment by Jonghakseo** [comment]
I apologise for the delay in responding. Let's take a look.

**Comment by lookis** [comment]
I found customDynamicImport doesn't work with await import, here is error:

```
src/pages/background/index.js:7681:16: ERROR: Expected ":" but found "dynamicImport"

Expected ":" but found "dynamicImport"
7679|                  const { FewShotPromptTemplate } = await
7680|          {
7681|            const dynamicImport = (path) => import(path);
   |                  ^
7682|            dynamicImport(
7683|            '../../../assets/js/few_shot.js')};
```

and this will resolve my problem

1. update vite >= 3.2
2. add ```modulePreload: false``` in vite.config.ts ```build``` part
3. change custom-dynamic-import.ts:

```
import type { PluginOption } from "vite";

export default function customDynamicImport(): PluginOption {
  return {
    name: "custom-dynamic-import",
    renderDynamicImport({ moduleId }) {
      if (!moduleId.includes("node_modules")) {  // <- dont modify any import from node_modules
        if (process.env.__FIREFOX__) {
          return {
            left: `
          {
            const dynamicImport = (path) => import(path);
            dynamicImport(browser.runtime.getURL('./') + 
            `,
            right: ".split('../').join(''))}",
          };
        }
        return {
          left: `
          {
            const dynamicImport = (path) => import(path);
            dynamicImport(
            `,
          right: ")}",
        };
      }
      return {
        left: "import(",
        right: ")",
      };
    },
  };
}
```

**Comment by Jonghakseo** [comment]
@lookis 

I've been testing with the solution you suggested and it seems to be working well. I'll raise a PR to reflect it, unless you have any other comments.

- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/195

**Comment by Jonghakseo** [comment]
@all-contributors please add @lookis for bug

**Comment by Jonghakseo** [comment]
@all-contributors please add @lookis for code

**Comment by Jonghakseo** [comment]
@all-contributors please add @chrisozgo99 for bug
