### ISSUE TITLE
dir.split(...).at is not a function

### ISSUE THREAD

**Issue by Js-Man-H5** [Jonghakseo/chrome-extension-boilerplate-react-vite#158]
node：v14.18.1
desc：git clones the main branch and installs dependencies without problems, but startup project error;
![image](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/62057975/40591358-c120-472d-98aa-4b1395a319d2)

**Comment by vishal-rathod-07** [comment]
Hey @Js-Man-H5 ,

This error might occur while using old versions of Node.

I've been able to fix the problem using Node: v18.17.0.
