### ISSUE TITLE
Content style leak to host page

### ISSUE THREAD

**Issue by ssikyou** [Jonghakseo/chrome-extension-boilerplate-react-vite#168]
The generated contentStyle<KEY>.chunk.css will contain some tailwind preset styles like:
```
html {
  line-height: 1.5; /* 1 */
  -webkit-text-size-adjust: 100%; /* 2 */
  -moz-tab-size: 4; /* 3 */
  -o-tab-size: 4;
     tab-size: 4; /* 3 */
  font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"; /* 4 */
  font-feature-settings: normal; /* 5 */
  font-variation-settings: normal; /* 6 */
}

```
The styles will affect the host page as we set it in our manifest.
Is there any way to inject the content style only to the injected App component?

**Comment by zxhmike** [comment]
@ssikyou AFAIK, the content styles are injected into the page. This is an expected behavior. Write more strict CSS rules for your extension. e.g. instead of `html`, use a container, `.my-extension-container`.

**Comment by ssikyou** [comment]
@zxhmike I agree with you. We should write strict CSS rules for our components. But the problem here is tailwind will generate some preset global styles for elements like "html" even if you do not write any classnames for your componets. You can refer to "dist/assets/css/contentStyleXXX.chunk.css" to understand what I'm talking about.

**Comment by zxhmike** [comment]
@ssikyou Ah, I know what you mean now. These styles are introduced by this line:
```
@tailwind base;
```

This is called Tailwind [Preflight](https://tailwindcss.com/docs/preflight), which is, according to the page, "a set of base styles for Tailwind projects that are designed to smooth over cross-browser inconsistencies and make it easier for you to work within the constraints of your design system."

Unfortunately, I can't find a way to make Tailwind generate these reset rules within a container class. However, there is an [issue](https://github.com/tailwindlabs/tailwindcss/discussions/7050) discussing this feature.

The workaround is simply removing this line. You might see some slight browser inconsistencies. Or, you can copy the generated reset rules and put them into a container class.

Hope this helps.

**Comment by Jonghakseo** [comment]
https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/53500778/ac63d737-c9f8-44f8-9027-42697c08442b

**Comment by ssikyou** [comment]
@zxhmike Thanks for your suggestion!
@Jonghakseo Great! This is the perfect solution AFAIK. Looking forward to it.

**Comment by Jonghakseo** [comment]
@ssikyou 

I raised a PR for the fix.

- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/171


I've reviewed it locally and found it to be working fine, but there may be something that I missed, so I'd appreciate it if you could get a pull against that branch or reference the changes and let me know.

**Comment by ssikyou** [comment]
@Jonghakseo I tried it locally and it does work.

**Comment by Jonghakseo** [comment]
@all-contributors please add @ssikyou for bug
