### ISSUE TITLE
VSCode debug

### ISSUE THREAD

**Issue by zxhmike** [Jonghakseo/chrome-extension-boilerplate-react-vite#170]
Hello community,

Is anyone able to debug a Chrome Extension is VSCode. I am able to add breakpoints in VSCode for the content scripts, but for the background script, I am not able to bind the breakpoints. Here is my launch.json.

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome",
      "url": "https://www.google.com",
      "runtimeArgs": ["--load-extension=${workspaceFolder}/myextension/dist"]
    }
  ]
}
```

I see this error.

![Screenshot 2023-08-14 at 12 16 46 PM](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/4087876/bfd37906-d225-47d3-880b-5e801732d764)

![Screenshot 2023-08-14 at 12 17 06 PM](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/4087876/f69ac962-7d0b-4065-9ec8-1281987c69be)

I am pretty sure that background.js is generated correctly with embedded source map. Also, I have this line in my vite.js:
```
    sourcemap: isDev ? "inline" : false,
```

Let me know if you have thoughts. Thanks in advance.

**Comment by Jonghakseo** [comment]
I don't use VSCODE, so it's hard for me to get into the details of this issue. If anyone is using that IDE, I'd love some help!

**Comment by PatrykKuniczak** [comment]
@zxhmike You solve that?

Cause it's open but no moves is done,
