### ISSUE TITLE
Maybe you want to use postcss-parent-selector for content styling

### ISSUE THREAD

**Issue by sturmenta** [Jonghakseo/chrome-extension-boilerplate-react-vite#178]
<img width="753" alt="Screenshot 2023-08-31 at 22 21 29" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/30802967/4606d04f-bb56-4bb1-b35f-659768c4fb53">

[stackoverflow source](https://stackoverflow.com/questions/69027407/chrome-extension-tailwind-css-interferes-with-websites-i-visit)
https://github.com/domwashburn/postcss-parent-selector

I add this in my project and solves my issue using this repo with injected content

**Comment by Jonghakseo** [comment]
Interesting! I will look into it. Thank you!
