### ISSUE TITLE
considered web-extension polyfill?

### ISSUE THREAD

**Issue by spencerc99** [Jonghakseo/chrome-extension-boilerplate-react-vite#18]
just wondering if you ever considered making this generally compatible with web extension to be used in firefox as well. Seems like most people use https://github.com/mozilla/webextension-polyfill

**Comment by Jonghakseo** [comment]
Unfortunately, Firefox compatibility is not considered.
Because I personally don't use Firefox. 😞

**Comment by Jonghakseo** [comment]
Although it's a bit cumbersome, it looks like you'll have to add the polyfill yourself.

**Comment by govza** [comment]
Coming across the issue, it looks like web-extension polyfill is [not needed ](https://github.com/mozilla/webextension-polyfill/issues/329#issuecomment-1188822881) anymore for manifest v3.
Firefox support though, achievable by small edition of manifest-parser (there is some small differences).
```js
static convertManifestToString(manifest: Manifest): string {
    if (process.env.__FIREFOX__) {
      manifest = this.convertToFirefoxCompatibleManifest(manifest);
    }
    return JSON.stringify(manifest, null, 2);
  }

  static convertToFirefoxCompatibleManifest(manifest: Manifest) {
    const manifestCopy = {
      ...manifest,
    } as { [key: string]: unknown };

    manifestCopy.background = {
      scripts: [manifest.background?.service_worker],
      type: "module",
    };
    manifestCopy.options_ui = {
      page: manifest.options_page,
      browser_style: false,
    };
    manifestCopy.content_security_policy = {
      extension_pages: "script-src 'self'; object-src 'self'",
    };
    delete manifestCopy.options_page;
    return manifestCopy as Manifest;
  }
```

and 
```
export default function customDynamicImport(): PluginOption {
  return {
    name: "custom-dynamic-import",
    renderDynamicImport() {
      if (process.env.__FIREFOX__) {
        return {
          left: `
        {
          const dynamicImport = (path) => import(path);
          dynamicImport(browser.runtime.getURL('./') + 
          `,
          // eslint-disable-next-line prettier/prettier
          right: ".split('../').join(''))}",
        };
      } ...
```
let me know if we want this as PR.

**Comment by ionutanin** [comment]
yes please

**Comment by Jonghakseo** [comment]
@govza 

I'm not a big fan of firefox, but I think this will help a lot of other people who are looking forward to firefox support.

If you could post a PR, I would be so grateful!
