### ISSUE TITLE
Pre commiter

### ISSUE THREAD

**Issue by PatrykKuniczak** [Jonghakseo/chrome-extension-boilerplate-react-vite#181]
**Is your feature request related to a problem? Please describe.**
Add pre commiter to project.

**Describe the solution you'd like**
Add e.g husky with commitlint, which check commit messages and pre-commiter run eslint and prettier before commit.

**Comment by Jonghakseo** [comment]
If you have a way of thinking, I'd be happy to make it a PR.

**Comment by PatrykKuniczak** [comment]
@Jonghakseo Don't laught i will do that 😆😆😅
