### ISSUE TITLE
I encountered the same problem on my vite project，has this problem been solved？

### ISSUE THREAD

**Issue by lwh795** [Jonghakseo/chrome-extension-boilerplate-react-vite#185]
I encountered the same problem on my vite project，has this problem been solved？

_Originally posted by @lwh795 in https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/157#issuecomment-1718927193_
            reload is a useful temporary solution

**Comment by PatrykKuniczak** [comment]
@lwh795 What's the point of that issue, if u comment in #157 and have the same error?

**Comment by Jonghakseo** [comment]
#157 

Issue #157 has been resolved.
