### ISSUE TITLE
When using shadcn/ui in the project, the TailwindCSS in the shadcn/ui component does not work

### ISSUE THREAD

**Issue by WalterZou** [Jonghakseo/chrome-extension-boilerplate-react-vite#190]
I'm using shadcn/ui ([import method](https://ui.shadcn.com/docs/installation/vite)) into my project, but the Tailwind CSS set on shadcn/ui components does not work. 

The code in `src/pages/newtab/newtab.tsx` is as follows:

```
const Newtab = () => {
  const theme = useStorage(exampleThemeStorage);
  
  return (
    <>
      <div className="text-white bg-lime-900 pt-2 pb-2 text-center">TailwindCSS</div>
      
      <CommandPattle className="text-white bg-lime-900 pt-2 pb-2 text-center"></CommandPattle>
    </>
  );
};

export default withSuspense(Newtab);
```

Where `CommandPattle` is an example [code](https://ui.shadcn.com/docs/components/command) using shadcn/ui.

The actual effect:

![image](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/3727208/e3e3bacd-0635-4bb3-b902-7b8076039662)

The expected effect:

![image](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/3727208/191cccad-f40b-4d9e-8766-894d986cf9de)

This looks like a compilation issue? How can I fix this? Need help, pls

**Comment by Maopy** [comment]
Same problem
