### ISSUE TITLE
Deploy New Tab as a webapp

### ISSUE THREAD

**Issue by hoathai** [Jonghakseo/chrome-extension-boilerplate-react-vite#198]
I would like to use the Popup as a Chrome extension, and the NewTab as a web app.

Would it be possible to deploy the NewTab page as a website?

**Comment by PatrykKuniczak** [comment]
@hoathai If I'm understand you.

You need a popup, this is obvious the core functionallity od extensions, and this repo
I think you can do it :)

But second case you can build your project, and on dist/src/newtab you have static js, which you can host everywhere you want, on some hostings or on your own :)

You can develop newtab with the rest of your extension and after you finish, then u can deploy it, and if u want to open this e.g from your popup, u can create chrome.window.create to open it from your chrome extension, and give a link to your hosted page.

I hope i'will be helpful 💯

**Comment by Jonghakseo** [comment]
@hoathai 

you can see [daily.dev](https://daily.dev/)

They are offering their own web app that manages articles in a new tab. Hope this helps!

**Comment by PatrykKuniczak** [comment]
@hoathai it's solved?

**Comment by PatrykKuniczak** [comment]
@Jonghakseo I think you can close it, if he want he can reopen

**Comment by Jonghakseo** [comment]
@PatrykKuniczak I agree.
