### ISSUE TITLE
 ERROR: Unexpected "." after install @segment/analytics-next and run the build

### ISSUE THREAD

**Issue by abdoKa** [Jonghakseo/chrome-extension-boilerplate-react-vite#234]
[vite:esbuild-transpile] Transform failed with 1 error:
src/pages/content/index.js:6:44: ERROR: Unexpected "."

Unexpected "."
4  |              const dynamicImport = (path) => import(path);
5  |              dynamicImport(
6  |              '../../../assets/js/index2.js')}.then(n => n.t);

**Comment by abdoKa** [comment]
```
import { Analytics } from "@segment/analytics-next";
import { SEGMENT_WRITE_KEY } from "./pages/content/constants";

const analytics = new Analytics({
  writeKey: SEGMENT_WRITE_KEY,
});

export default analytics;
```

for example after call `analytics.page()` and run yarn build I get this error:

`[vite:esbuild-transpile] Transform failed with 1 error:
src/pages/content/index.js:6:50: ERROR: Unexpected "."

Unexpected "."
4  |            const dynamicImport = (path) => import(path);
5  |            dynamicImport(
6  |            '../../../assets/js/index.7aa86259.js')}.then(n => n.c);
   |                                                    ^

error during build:
Error: Transform failed with 1 error:
src/pages/content/index.js:6:50: ERROR: Unexpected "."`

**Comment by abudhakeer** [comment]
Is there any update with this issue? I face similar situation when i try to use Supabase in my project, like

```
import { createClient } from "@supabase/supabase-js";

const _supabase = createClient(
  SUPABASE_URL,
  SUPABASE_KEY
);
```

**Comment by abudhakeer** [comment]
I was able to solve this issue using this approach - https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/157#issuecomment-1754429808
