### ISSUE TITLE
Redux Toolkit + Redux Presist

### ISSUE THREAD

**Issue by mehardiknaik** [Jonghakseo/chrome-extension-boilerplate-react-vite#237]
Please help me with redux Toolkit for popup page and store state in storage with redux presist

**Comment by Jonghakseo** [comment]
Can you describe the issue you're experiencing in more detail? Providing information from the codebase or a public repo would be great.

**Comment by PatrykKuniczak** [comment]
@mehardiknaik i probably know which tutorial you watched and i can suggest you, to use react context + react query, its also good solution, if you have trouble with redux

**Comment by Jonghakseo** [comment]
In my opinion, using simple redux on popup pages and applying redux persist is not particularly different for chrome extensions.

I'll close the issue since there's no special context, but please reopen if you have more information or if it's a tangential issue.
