### ISSUE TITLE
In the error window, `WebSocket connection to...` error and `Reload server disconnected` warning continue to appear

### ISSUE THREAD

**Issue by wonkyDD** [Jonghakseo/chrome-extension-boilerplate-react-vite#245]
**Describe the bug**

If I check at chrome://extensions/?errors=<extension_id>,
it shows a warning related to `utils/reload/initReloadClient.ts`

`WebSocket connection to...` error

<img width="615" alt="image" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/81248624/65d05e5a-210d-49b2-9414-6b15da65c3eb">

`Reload server disconnected` warning

<img width="624" alt="image" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/81248624/6e904fb7-117d-44bf-bc46-c65db8b6c8ba">

**To Reproduce**

1. git clone https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite.git
2. pnpm install && pnpm dev
3. Load unpacked extension in the dist/ path
4. shut down dev server in terminal with `ctrl + c`
5. reload extension in **chrome://extensions/** 

**Expected behavior**
I don't want to keep getting errors and warnings when I shut down the dev server.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac 13.0.1
 - Browser 118.0.5993.117
 - Node Version v18.17.1

**Additional context**

If this is the intended behavior, I humbly accept it.

**Comment by Jonghakseo** [comment]
I'm gonna check ASAP.

**Comment by Jonghakseo** [comment]
Aha... Is this about the warn on socket server disconnected?
That's by design, as it may not be the user's intention for the dev server for HMR to shut down in a development environment.

If you have any suggestions on how to improve this, please feel free!

**Comment by wonkyDD** [comment]
@Jonghakseo I understand what you mean, thanks for the quick response.

**Comment by IzaGz** [comment]
@Jonghakseo this error causes constantly spamming in console with this massages
its unavailable to read console 
<img width="1054" alt="Снимок экрана 2024-06-11 в 00 54 16" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/19924220/d72e685c-bb3a-43e6-bf39-7199f1377c4e">
