### ISSUE TITLE
Enable again deps bot

### ISSUE THREAD

**Issue by PatrykKuniczak** [Jonghakseo/chrome-extension-boilerplate-react-vite#253]
I think good idea is enable again deps bot, after #251 we have everything except Vite, up to date.

On vite and plugin for them, we can have this PR open, till they fix this, and we can easly update to the latest version, if we have it open, 
we will remember to check it ;)

**Comment by Jonghakseo** [comment]
I disabled the dependency update bot because it was noisy, but I agree with you.
