### ISSUE TITLE
Use vitest instead of jest for testing

### ISSUE THREAD

**Issue by wonkyDD** [Jonghakseo/chrome-extension-boilerplate-react-vite#257]
I suggest replacing the testing with **Vitest** instead of jest.    

<br>

**Vitest** guarantees a faster pace of testing and also integrates better with vite, which we are currently using.   
We don't need `jest.confg.js` anymore.

<br>

With vitest, you can remove the `jest`, `jest-environment-jsdom`, `ts-jest`, and `@types/jest` packages
and replace them with `vitest` and `jsdom` for brevity.

<br>

If you don't mind, would you mind assigning it to me?
I've already seen it working fine locally. Thanks for reading, and keep it up!

**Comment by wonkyDD** [comment]
[use-vitest](https://github.com/wonkyDD/chrome-extension-boilerplate-react-vite/tree/use-vitest)

**Comment by Jonghakseo** [comment]
> I suggest replacing the testing with **Vitest** instead of jest.
> 
> 
> **Vitest** guarantees a faster pace of testing and also integrates better with vite, which we are currently using. We don't need `jest.confg.js` anymore.
> 
> 
> With vitest, you can remove the `jest`, `jest-environment-jsdom`, `ts-jest`, and `@types/jest` packages and replace them with `vitest` and `jsdom` for brevity.
> 
> 
> If you don't mind, would you mind assigning it to me? I've already seen it working fine locally. Thanks for reading, and keep it up!

Sure. Can you create a pull request for me?

**Comment by PatrykKuniczak** [comment]
@Jonghakseo If i will finish my own project, i will take a look for that issue, and try to solve that, then i will give info to @wonkyDD  and he can start working again :)

**Comment by govza** [comment]
BTW, using puppeteer/playwright to load the extension into browser and run e2e tests, sometimes comes handy.
Maybe bring them here?

**Comment by Jonghakseo** [comment]
- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/279

**Comment by PatrykKuniczak** [comment]
@wonkyDD it's merged right now, feel free to start your work again :)
