### ISSUE TITLE
Add to the Style Library Setup Guide README

### ISSUE THREAD

**Issue by Jonghakseo** [Jonghakseo/chrome-extension-boilerplate-react-vite#263]
**Is your feature request related to a problem? Please describe.**

People have different style libraries they like to use, and adding a specific library to the boilerplate has more downsides than upsides.

**Describe the solution you'd like**
Instead of adding specific libraries to the boilerplate, write a setup guide for each library and add it to the README.
(e.g. Emotion, Chakra UI)

- [x] Chakra UI - https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/270
- [ ] Emotion
- [ ] tailwindcss
- [x] Twind - https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/275

**Additional context**
- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/243#issuecomment-1793666057

**Comment by Jonghakseo** [comment]
Chakra UI

- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/270

**Comment by PatrykKuniczak** [comment]
> Chakra UI
> 
> * [docs: add style library guide (Chakra UI) #270](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/270)

IMO better idea is edit description, and there link PR's, cause it can dissapear when there's a lot of comments.

We don't have many contributors but in larger libs like MUI, all essential info is on Issue/PR description :)

**Comment by wonkyDD** [comment]
@Jonghakseo With your permission, could I add a style guide for [shadcn/ui](https://ui.shadcn.com/)?

**Comment by Jonghakseo** [comment]
> @Jonghakseo With your permission, could I add a style guide for [shadcn/ui](https://ui.shadcn.com/)?

Sure!

**Comment by 2hari** [comment]
@wonkyDD can you share some updates ?
