### ISSUE TITLE
0.12.0 version tag typo

### ISSUE THREAD

**Issue by PatrykKuniczak** [Jonghakseo/chrome-extension-boilerplate-react-vite#264]
Latest version should be 0.12.0, it's typo here:

https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/releases/tag/0.0.2

**Comment by PatrykKuniczak** [comment]
@Jonghakseo I change it already, i was opened it as info issue :)

**Comment by Jonghakseo** [comment]
Thx!
