### ISSUE TITLE
Content Script style <KEY> not updated in manifest on hot reload

### ISSUE THREAD

**Issue by gavinhow** [Jonghakseo/chrome-extension-boilerplate-react-vite#294]
**Describe the bug**
When using `pnpm dev`. The first time it builds it works correctly, however when I change the styles, it rebuilds the styles with a new cacheKey and puts that in the `dist` folder, however the `manifest.json` still has the old key so changes are not reflected in the browser. 

**To Reproduce**
1. run `pnpm dev`
2. change content script style, automatic rebuild
3. `manifest.json` has old key

**Expected behavior**
`manifest.json` should be updated with the latest key.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Node Version 18.16.1

**Comment by PatrykKuniczak** [comment]
@gavinhow Theres' more issue with this, i have also #296

If you can work without css for now, let's try to use my workaround, it's linked in this PR on description.

I hope it can help you for now, i'm sadgeful busy but maybe on this weekend i have time to investigate that or @Jonghakseo can solve this :)

**Comment by Jonghakseo** [comment]
@gavinhow 

I apologize for this bug.
I should have tested and fixed the feature more thoroughly.

Thanks for the report.

**Comment by Jonghakseo** [comment]
@all-contributors please add @gavinhow for bug
