### ISSUE TITLE
Error on trying to establish websocket connection

### ISSUE THREAD

**Issue by PatrykKuniczak** [Jonghakseo/chrome-extension-boilerplate-react-vite#297]
I have react router on my project, and on redirection ws server lost connection, and i have error like that in the console:

![image](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/64608510/c35426c0-b432-4fb2-8ef4-15fc5d411f8b)

Plugin works well, but sth isn't good.

I was created new label low-priority, for issues like this

**Comment by PatrykKuniczak** [comment]
@Jonghakseo I see now it's happened everytime, not only on redirecting, my bad i change title of issue, let's check it if u have time ;)

**Comment by Jonghakseo** [comment]
Yeah I didn't see the problem when I created a react hash router locally and redirected it, so I guess it's just another side effect.

**Comment by PatrykKuniczak** [comment]
@Jonghakseo That's not related to template, it's happened because if some page e.g default/start chrome page don't accept content scripts or script is not loaded to some pages, then message cannot be send, and this error occur then.

https://stackoverflow.com/a/73276111/18155752

I close this :)
