### ISSUE TITLE
Unlink error broke the script

### ISSUE THREAD

**Issue by PatrykKuniczak** [Jonghakseo/chrome-extension-boilerplate-react-vite#304]
Sometimes i had this error, this once per day, or a little often but it happened

![image](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/64608510/4e4fb24c-2867-4cc2-907c-5b852cf9745f)

It's happened on rebuild i think, cause broke when 'build:watch' running

**Comment by lealahm** [comment]
Same here, I also get this error

**Comment by Jonghakseo** [comment]
- https://stackoverflow.com/questions/55212864/error-ebusy-resource-busy-or-locked-rmdir

Hmmm. Maybe one of the solutions suggested in the link above will work?

**Comment by PatrykKuniczak** [comment]
@Jonghakseo Ye, Windows 11 with AMD CPU

**Comment by PatrykKuniczak** [comment]
> * https://stackoverflow.com/questions/55212864/error-ebusy-resource-busy-or-locked-rmdir
> 
> Hmmm. Maybe one of the solutions suggested in the link above will work?

Maybe, but that's not a good solution, cause if somebody use this template, i'm pretty sure they don't want to configure sth else additionally for windows, to work without any errors

**Comment by lealahm** [comment]
> @lealahm Can you give us some information about your environment? Is it a Windows operating system?

Yes, windows 11

**Comment by PatrykKuniczak** [comment]
@Jonghakseo It's freaking annoying, it's happened more often, i don't develop more last time, now i must hurry done my project and i develop more, and i see it's happened once per about 10 reload

**Comment by PatrykKuniczak** [comment]
@Jonghakseo This is the highest priority, cause it's freaking annoying, start and stop, start and stop, maaan.

We must to repair this, in this week i want to done MVP for my project, and i can contribute more :)

**Comment by PatrykKuniczak** [comment]
https://github.com/orgs/community/discussions/50143#discussioncomment-5323603

It works to me

**Comment by PatrykKuniczak** [comment]
Stop working ... 

I have no power here xD

**Comment by Jonghakseo** [comment]
> @lealahm [github.com/orgs/community/discussions/50143#discussioncomment-5323603](https://github.com/orgs/community/discussions/50143#discussioncomment-5323603)
> 
> It works to me, i think we should document this, or create sh script or sth in js, which clear temp, for avoid this issue, maybe it's not the best issue, to clear temp of dev machine, but hymm, we should think about it @Jonghakseo
> 
> Temp isn't sensitive data, i don't use it never, apps create it on next start, cause as folder name say, it's temporary, maybe it isn't bad idea to clear %temp% on windows on start this template, let give me a feedback what you think

If it's a problem that can be solved with the `npm cache clean` command, I think it would be good to mention it in the readme. Am I understanding this correctly?

**Comment by PatrykKuniczak** [comment]
> readme

It's not working for me, i was trying this and clean temp.

Have you any idea?

**Comment by Jonghakseo** [comment]
I've been using windows for a long time, so I have no concept of the temp folder. 
How does emptying the temp folder work? Do you have a example script?

**Comment by PatrykKuniczak** [comment]
> I've been using windows for a long time, so I have no concept of the temp folder. How does emptying the temp folder work? Do you have a example script?

it has temporary data from all installed apps on PC, but this solution didn't work.

I don't use any script, i open it manually

**Comment by Jonghakseo** [comment]
> it has temporary data from all installed apps on PC, but this solution didn't work.

Which solution are you referring to? I checked the solution attached in the link (emptying the temp folder altogether) and thought it worked well for you.

I'm not sure what you're asking for an opinion on.

**Comment by PatrykKuniczak** [comment]
> > it has temporary data from all installed apps on PC, but this solution didn't work.
> 
> Which solution are you referring to? I checked the solution attached in the link (emptying the temp folder altogether) and thought it worked well for you.
> 
> I'm not sure what you're asking for an opinion on. Is there anything I can help you with?

i was try both options from this link above, i was use npm clean cache and remove everything from %temp%

I need to try it again, and i will send you feedback

**Comment by PatrykKuniczak** [comment]
@Jonghakseo Any moves forward?

**Comment by Jonghakseo** [comment]
> @Jonghakseo Any moves forward?

No I haven't paid attention to it at all in recent weeks, I'll try to look into it this weekend.

**Comment by PatrykKuniczak** [comment]
@Jonghakseo After your last big refactor (turborepo) it works perfect <3
