### ISSUE TITLE
Can't add a custom Content Script folder

### ISSUE THREAD

**Issue by lealahm** [Jonghakseo/chrome-extension-boilerplate-react-vite#306]
**Describe the bug**
I want to add my own custom content script folder that contains code that only evokes whenever the user clicks on a button in the popup.tsx. I figured out that I had to add the folder path in the **vite.config.ts** file in order to add the folder in the dist directory when build for production. I used the exact same code in the newcontent folder that there is in the content folder ( Changed the import paths ), but whenever I launch the Chrome extension and visit any webpage the default content script won't work and throws up this error:- **Uncaught SyntaxError: Cannot use import statement outside a module**

After much digging, I found out that its mostly because we just can't declare two content script folders in the vite.config.ts file.

**Screenshots**
![error](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/151762001/384e14fb-d209-47f9-b0f6-2e956576e85f)

**Additional context**
I am not sure what could be the solution to this problem, I just want a default content script from the manifest.js file and another content script folder that injects the scripts based on the user interactions in the popup file or background.ts

**Comment by PatrykKuniczak** [comment]
https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/246/files

That's already fixed, this issue seems to be duplicated with #160

**Comment by efanibi25** [comment]
I couldn't get the previous answer to work so I used this

https://github.com/vitejs/vite/issues/8023
Then modified the package.json

pnpm build:hmr && (run-p wss build:watch build2:watch build3:watch)"

**Comment by lealahm** [comment]
@PatrykKuniczak, Not really, I still couldn't have two different content script folders, one is added on every page through manifest and the other is only added through chrome.executeScript

**Comment by PatrykKuniczak** [comment]
> @PatrykKuniczak, Not really, I still couldn't have two different content script folders, one is added on every page through manifest and the other is only added through chrome.executeScript

It's even possible in pure chrome extension, without React?

**Comment by lealahm** [comment]
@PatrykKuniczak, Yes, its possible with simple vanilla JS project, we can have two different content scrip files, one would be loaded on the every page automatically using manifest and the other only through chrome.scripting.executeScript

**Comment by PatrykKuniczak** [comment]
@lealahm Ok, now i'm understand, you don't want to create second content script, only folder from where you can load next script.

If you have any solution, maybe you want to open PR, and want to work on that, we can help.

I think if you can issue with Vite, that's probably duplicated name issue, let's try to create some suffix.

Maybe we want to implement it for template, but as a docs description or if it don't break sth, it can be places in code, but comment that and on dosc, devs have a instruction step by step, what should to do, for enable multiple content scripts, cause i think it's not very popular to create several content scripts. :)

**Comment by lealahm** [comment]
@PatrykKuniczak, I am really sorry but I don't get what you said in the above message, are you implying that we should fix this issue of enabling both automatic and injected content script and comment out the injected code and mention that in the documentation for people who wants to implement both?

**Comment by lealahm** [comment]
@PatrykKuniczak, is there any way I can help with the above issue?

**Comment by PatrykKuniczak** [comment]
@lealahm Maybe im not clear.

I mean let's create it on code, but don't use it on default, i think it's not necessary, because we need to create additional folder with this content script, and let's think about people which don't want to create content script at all, they need to remove more code than now.

Let's create support for additional content scripts but comment code which implement that, and don't create additional folder.
Over that create information in docs, which lines dev should uncomment, to back alive this feature, and with what name they need to create folder, to feature works properly.

My english isn't very good, if you need more clarification let me know, i'm try my best <3

You can help by opening PR with you workaround, and we can see that, or if it's not works for you, we can have a base to work on, and then we can try to find the best solution for that case, now i have more time, cause i'm almost finish my own project :)

**Comment by lealahm** [comment]
@PatrykKuniczak, Thank you so much for the support, you are awesome :)

This is what I tried, I created another folder in the src/pages with the name injectedContentscript and added this in the vite.config.ts file 

`
// vite.config.ts
{
  //...
  content: resolve(pagesDir, 'content', 'index.ts'),
  injectedContentscript: resolve(pagesDir, 'injectedContentscript ', 'index.ts'), // added this
  background: resolve(pagesDir, 'background', 'index.ts'),
}
`
and then in my popup.tsx I had this code :-

`
const injectScript = async () => {
    const [tab] = await chrome.tabs.query({ currentWindow: true, active: true });
    console.log(tab.id)
    chrome.scripting.executeScript({
            target: { tabId: tab.id },
            files: ['src/pages/injectedContentscript/index.js'],
    });
`

**Comment by PatrykKuniczak** [comment]
@lealahm Ok, that's good, but what if dev want to inject script after script, u know after automatically content (default) want to run script on that, that's should be done also for content script, cause if you don't open popup, this script didn't run.

I think your solution is good, but we need to document also that case.

If you can, let's open a PR with this vite config and comment this code and then create description on README.md how to enable that, and place here also a usecase like you do it here, paste a code snippet like this from your popup.tsx and create also similiar for devs which want to run this script in background/content script.

If you do it, feel free to assign me as a reviewer or send questions here if you have any.

You're awesome :)

**Comment by PatrykKuniczak** [comment]
> @PatrykKuniczak, Hello, I just did a Pull request with the name inject-content-script

I will see it later and send feedback 😁

**Comment by lealahm** [comment]
@PatrykKuniczak, Np, take your time, once again Thank you so much :)

**Comment by romaindequidt** [comment]
@Jonghakseo may you explain why "Automatically supporting multiple content scripts may require a change to a framework rather than boilerplate" ? 

1. there is only one content script entry point, is'nt it ?
2. it was a misunderstading ? @lealahm is not talking about "Content script" but rather "Injected script" ?

Actually, I have the same trouble as @lealahm, I have to inject script in page because DOM exposed to the Chome extension is not the "real" DOM. It lakes some infos & methods (e.g. I can't know if an element is a shadow root, and I can't explore them)

So, I wanted to generate script and inject it in all the website I want:
```
const injectedContentscript= document.createElement('script')
injectedContentscript.setAttribute('type', 'module') // to accept `import`
const injectedContentscriptPath = chrome.extension.getURL('src/pages/injectedContentscript/index.js')
injectedContentscript.src = injectedContentscriptPath
(document.head || document.documentElement).appendChild(injectedContentscript)
```
(this is a script running in my `content script` at `document_start` time)

I didn't know that method [executescript](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/executeScript) and I don't konw if I can do the same thing with it.

But adding this `injectedContentscript: resolve(pagesDir, 'injectedContentscript ', 'index.ts'),` make the `src/pages/content/index.js` generated file totally different.

Before, I have `__vitePreload` definition and usage for each imported files.
While, after addind this line in the `vite.config.ts`, I have `import` and `__vite__mapDeps` definition and usages.

May you explain me the reason ? the root cause?

Others questions:
- in `rollupOptions`, why do we use input and ouput, can we not just use default settings and naming convention ?
- related question: why we use `cacheInvalidationKey` ? if file content change, hash change ? so the browsing cache will be automatically updated, isn't it?

Thanks for your help.

**Comment by Jonghakseo** [comment]
I understood your question to mean that we need to support multiple content scripts in the manifest.json. For inject, we can use the script api or implement it the way you described.

As for the issue you are experiencing (vite-preload-script), it seems to be solved with inline processing, could you please double check?

To answer your other question:

The reason for explicitly declaring input and output in rollupOptions was to limit the entry points for the build output to each context, and to control the output name of that output and make it more recognizable in the manifest.

The cacheInvalidationKey is used for css revalidation of the contentStyle, and was added to bypass an issue where changes to the css were not properly reflected on hmr behavior (browser caching issues

**Comment by mondaychen** [comment]
I'm having the exact same problem. For some reason, everything works fine when I have only one content script entry, but when I add a second one, neither of them work.
The compiled content script file looks different too. When it's working, it looks like this:
```
const scriptRel = function detectScriptRel() {
  const relList = typeof document !== "undefined" && document.createElement("link").relList;
  return relList && relList.supports && relList.supports("modulepreload") ? "modulepreload" : "preload";
}();
const assetsURL = function(dep) {
  return "/" + dep;
};
const seen = {};
const __vitePreload = function preload(baseModule, deps, importerUrl) {
  if (!deps || deps.length === 0) {
    return baseModule();
  }
  const links = document.getElementsByTagName("link");
  return Promise.all(deps.map((dep) => {
    dep = assetsURL(dep);
    if (dep in seen)
      return;
    seen[dep] = true;
    const isCss = dep.endsWith(".css");
    const cssSelector = isCss ? '[rel="stylesheet"]' : "";
    const isBaseRelative = !!importerUrl;
    if (isBaseRelative) {
      for (let i = links.length - 1; i >= 0; i--) {
        const link2 = links[i];
        if (link2.href === dep && (!isCss || link2.rel === "stylesheet")) {
          return;
        }
      }
    } else if (document.querySelector(`link[href="${dep}"]${cssSelector}`)) {
      return;
    }
    const link = document.createElement("link");
    link.rel = isCss ? "stylesheet" : scriptRel;
    if (!isCss) {
      link.as = "script";
      link.crossOrigin = "";
    }
    link.href = dep;
    document.head.appendChild(link);
    if (isCss) {
      return new Promise((res, rej) => {
        link.addEventListener("load", res);
        link.addEventListener("error", () => rej(new Error(`Unable to preload CSS for ${dep}`)));
      });
    }
  })).then(() => baseModule()).catch((err) => {
    const e = new Event("vite:preloadError", { cancelable: true });
    e.payload = err;
    window.dispatchEvent(e);
    if (!e.defaultPrevented) {
      throw err;
    }
  });
};
__vitePreload(() => import("../../../assets/js/injected.js"), true ? __vite__mapDeps([]) : void 0);
console.log("content loaded");
function __vite__mapDeps(indexes) {
  if (!__vite__mapDeps.viteFileDeps) {
    __vite__mapDeps.viteFileDeps = []
  }
  return indexes.map((i) => __vite__mapDeps.viteFileDeps[i])
}
```

When it's not working, both complied files look like this:
```
import { _ as __vitePreload } from "../../../assets/js/preload-helper.js";
__vitePreload(() => import("../../../assets/js/injected.js"), true ? __vite__mapDeps([]) : void 0);
console.log("content loaded");
function __vite__mapDeps(indexes) {
  if (!__vite__mapDeps.viteFileDeps) {
    __vite__mapDeps.viteFileDeps = []
  }
  return indexes.map((i) => __vite__mapDeps.viteFileDeps[i])
}
```

Looks like the biggest difference is whether `__vitePreload` is inlined or imported.

**Comment by tngflx** [comment]
Hmm still the same inline vite preload problem.. So does switching to turbopack made significant speed change?

**Comment by PatrykKuniczak** [comment]
> Hmm still the same inline vite preload problem.. So does switching to turbopack made significant speed change? I missed so many updates on this repo already

That thread is for legacy of course, we're have a better structure and performance now :)

**Comment by AaronLayton** [comment]
> import { _ as __vitePreload } from "../../../assets/js/preload-helper.js";

Did you get this part working? I too have missed so many updates on this repo so have been manually updating package references. It seems I am not getting the quoted line in my `content/index.ts` file

if I comment out the `components/Demo` then everything works, but if I leave it in then I get the `import` file and errors saying I can use imports from this file

```tsx
/**
 * @description
 * Chrome extensions don't support modules in content scripts.
 */
//import("./components/Demo");
```

**Comment by Jonghakseo** [comment]
- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/494

Check above PR
