### ISSUE TITLE
How to introduce scss or css in Content UI

### ISSUE THREAD

**Issue by webLiang** [Jonghakseo/chrome-extension-boilerplate-react-vite#307]
<img width="784" alt="image" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/38065991/899c119c-7918-4200-b858-db08cd195fce">

**Comment by webLiang** [comment]
Like this
<img width="804" alt="image" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/38065991/20b07398-89f5-429e-991d-bb96505f1eb9">

**Comment by webLiang** [comment]
Finally discovered this style pour in

<img width="873" alt="image" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/38065991/ed01b782-2289-4f8d-a656-63062388b5c8">

<img width="907" alt="image" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/38065991/54a265d2-2004-4398-a665-cd4ea94ddcb0">

**Comment by Jonghakseo** [comment]
This is a good solution. I'll add it to the code for others to reference!

#313

**Comment by webLiang** [comment]
Thanks   ♪(･ω･)ﾉ

**Comment by tngflx** [comment]
> Like this <img alt="image" width="804" src="https://private-user-images.githubusercontent.com/38065991/286856294-20b07398-89f5-429e-991d-bb96505f1eb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNjE3NDAsIm5iZiI6MTcwNTI2MTQ0MCwicGF0aCI6Ii8zODA2NTk5MS8yODY4NTYyOTQtMjBiMDczOTgtODlmNS00MjllLTk5MWQtYmI5NjUwNWYxZWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDE5NDQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyYzY4YzU4ZTYwZWZhNWJjNzY5ZDYwOGU2ODdkMzFmOGE4OTZhMWUyMTE0NWZkYzk1M2E2Yzg1Njk3ODFjYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8fUjSAz4PQOpCN03PTkAlFZ2KZIRDH9bfjoeGvhG5kc">

hmm plasmo doesnt release source code how they do it right with css? Do you use sny chrome extension framework?
