### ISSUE TITLE
Have to reload when scss is changed

### ISSUE THREAD

**Issue by NAMU1105** [Jonghakseo/chrome-extension-boilerplate-react-vite#32]
Hi, thanks for the good template.

I was working on this template and found out that 
I need to reload the extension file on chrome://extension to see the updated .scss file

can you improve on this?

thank you

**Comment by Jonghakseo** [comment]
Sorry for my late reply. Can you tell me in detail under what circumstances hmr doesn't work?

https://user-images.githubusercontent.com/53500778/205446614-c8ee96b8-6dfd-427b-9221-0a6fe894dfaf.mov

If possible, I would appreciate it if you could test it with the latest version and let me know.

**Comment by nerdchanii** [comment]
Hello! First of all, thank you for making a good template. Thanks to you, I was able to get started easily. 

I am also experiencing the same problem as the issue, so I leave an issue.

as you reproduced above, css is working well with HMR with `newTab`, `popup`, `option`. However, it is not applied when the scss file under '/content' is changed in the process of working.

So now, we have to manually reload the extensions.

reproduce



https://user-images.githubusercontent.com/63002393/222114378-cd5bdea2-ad80-490c-b6a2-9378cefd1b5d.mov

**Comment by Jonghakseo** [comment]
@nerdchanii 

Thanks for posting the replay video. This issue has been resolved in the PR below, and the style of contentscript is now updated normally.

https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/55

https://user-images.githubusercontent.com/53500778/223736753-c89153d1-6c5e-4d8a-b406-8bf1f6882b87.mov

**Comment by nerdchanii** [comment]
@Jonghakseo Oh! Looks so cool! Thanks you, I appreciate your works 🙇🏻

**Comment by Jonghakseo** [comment]
@all-contributors please add @NAMU1105 for bug
