### ISSUE TITLE
How you do debug?

### ISSUE THREAD

**Issue by neilfranci** [Jonghakseo/chrome-extension-boilerplate-react-vite#321]
I'm using VSCode, I don't know what IDE you guys are using but I can't find a way to do it.
- I just simply want to trace down what the state is holding, and where am I in the code...
- I had to write a bunch of console.log() and read a long list of logs to figure out what was wrong with the code.
- I can't add breakpoints etc..
I've tried https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/170#issue-1850114764 but placing the breakpoint in VSCode does nothing...

Is there no dev tools for web extension? Thanks 😓

**Comment by neilfranci** [comment]
But I still wonder if we can debug in the .tsx file.. because .js is a mess

**Comment by marcin-koziel** [comment]
My solution might not be a one-size-fits-all and could entirely depend on the structure of your application, but I have it working consistently!

First, ensure your `launch.json` and `vite.config.ts` files are properly configured. Here's a detailed guide to help you:

### launch.json:
This configuration will set up a Chrome debugger instance and map your project src files to dist files.

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Chrome against localhost",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceFolder}/your-extension-folder-name",
      "runtimeArgs": [
        "--load-extension=${workspaceFolder}/dist",
      ],
      "sourceMaps": true,
      "sourceMapPathOverrides": {
        "fpmkpflgklcbdcpbdhjpopcnoaneepjf://*": "${workspaceFolder}/*"
      },
      "trace": true
    }
  ]
}
```

### vite.config.ts:
Ensure all the files you want to debug are included in `rollupOptions` and output them respectively. Also, make sure `sourcemap` is set to true.

```typescript
const getFiles = (dir) => glob.sync(`${dir}/**/*.{ts,tsx,js,jsx}`);

export default defineConfig({
  resolve: {
    alias: {
      '@root': rootDir,
      '@src': srcDir,
      '@assets': assetsDir,
      '@pages': pagesDir,
      '@modules': modulesDir,
    },
  },
  plugins: [
    makeManifest({
      getCacheInvalidationKey,
    }),
    react(),
    customDynamicImport(),
    addHmr({ background: enableHmrInBackgroundScript, view: true }),
    isDev && watchRebuild({ afterWriteBundle: regenerateCacheInvalidationKey }),
  ],
  publicDir,
  build: {
    outDir,
    sourcemap: isDev,
    minify: isProduction,
    modulePreload: false,
    reportCompressedSize: isProduction,
    emptyOutDir: !isDev,
    rollupOptions: {
      input: {
        devtools: resolve(pagesDir, 'devtools', 'index.html'),
        panel: resolve(pagesDir, 'panel', 'index.html'),
        content: resolve(pagesDir, 'content', 'index.ts'),
        background: resolve(pagesDir, 'background', 'index.ts'),
        contentStyle: resolve(pagesDir, 'content', 'style.scss'),
        popup: resolve(pagesDir, 'popup', 'index.html'),
        newtab: resolve(pagesDir, 'newtab', 'index.html'),
        options: resolve(pagesDir, 'options', 'index.html'),
        sidepanel: resolve(pagesDir, 'sidepanel', 'index.html'),
        // Add all files from modules, utils, and components as entries
        ...getFiles(resolve(srcDir, 'modules')).reduce((acc, file) => {
          acc[file.replace(srcDir, '').replace(/\.[^/.]+$/, "")] = file;
          return acc;
        }, {}),
        ...getFiles(resolve(srcDir, 'utils')).reduce((acc, file) => {
          acc[file.replace(srcDir, '').replace(/\.[^/.]+$/, "")] = file;
          return acc;
        }, {}),
        ...getFiles(resolve(srcDir, 'components')).reduce((acc, file) => {
          acc[file.replace(srcDir, '').replace(/\.[^/.]+$/, "")] = file;
          return acc;
        }, {}),
      },
      output: {
        entryFileNames: ((chunkInfo) => {
          const { facadeModuleId } = chunkInfo;
          const root = rootDir.replace(/\\/g, '/');
          if (
            facadeModuleId.includes('src/modules') ||
            facadeModuleId.includes('src/utils') ||
            facadeModuleId.includes('src/components')
          ) {
            const path = facadeModuleId.replace(`${root}/`, '').replace('.ts', '.js');
            return `${path}`;
          } else if (facadeModuleId.includes('src/pages')) {
            return 'src/pages/[name]/index.js';
          } else if (facadeModuleId.includes('node_modules')) {
            return 'node_modules/[name]/index.js';
          }
          return '[name].js';
        }) as any,
        chunkFileNames: isDev ? 'assets/js/[name].js' : 'assets/js/[name].[hash].js',
        assetFileNames: assetInfo => {
          const { name } = path.parse(assetInfo.name);
          const assetFileName = name === 'contentStyle' ? `${name}${getCacheInvalidationKey()}` : name;
          return `assets/[ext]/${assetFileName}.chunk.[ext]`;
        },
      },
    },
  },
  test: {
    globals: true,
    environment: 'jsdom',
    include: ['**/*.test.ts', '**/*.test.tsx'],
    setupFiles: './test-utils/vitest.setup.js',
  },
});
```

1. **Ensure Source Maps in `tsconfig.json`**:
   ```json
   {
     "compilerOptions": {
       "sourceMap": true,
       ...
     }
   }
   ```

2. **Start the Development Server**:
   Make sure your development server is running: `npm run dev`.

3. **Debug in VSCode**:
   Open the Debug panel in VSCode (View -> Debug or `Ctrl+Shift+D`), select "Launch Chrome against localhost" and start debugging!

- Place breakpoints in your source TypeScript files.
- If breakpoints are not hitting, check the `outDir` in your Vite config and ensure it matches where the files are being output (e.g., .js & .js.map).
- Ensure that Chrome is opening with the correct debugging flags.

I hope this helps! It was a long tedious process to get to work, but there is a light at the end of the tunnel, I assure you!

![image](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/60167559/06bf5ab1-3c82-4871-958c-e3635b00a0b5)

**Comment by PatrykKuniczak** [comment]
> My solution might not be a one-size-fits-all and could entirely depend on the structure of your application, but I have it working consistently!
> 
> First, ensure your `launch.json` and `vite.config.ts` files are properly configured to debug. I included additional files from modules, utils, and components in my Chrome extension.
> 
> ### launch.json:
> This configuration will set up a Chrome debugger instance and map your project src files to dist files.
> 
> ```json
> {
>   "version": "0.2.0",
>   "configurations": [
>     {
>       "name": "Launch Chrome against localhost",
>       "type": "chrome",
>       "request": "launch",
>       "url": "http://localhost:3000",
>       "webRoot": "${workspaceFolder}/your-extension-folder-name",
>       "runtimeArgs": [
>         "--load-extension=${workspaceFolder}/dist",
>       ],
>       "sourceMaps": true,
>       "sourceMapPathOverrides": {
>         "fpmkpflgklcbdcpbdhjpopcnoaneepjf://*": "${workspaceFolder}/*"
>       },
>       "trace": true
>     }
>   ]
> }
> ```
> 
> ### vite.config.ts:
> Ensure all the files you want to debug are included in `rollupOptions` and output them respectively. Also, make sure `sourcemap` is set to true.
> 
> ```typescript
> const getFiles = (dir) => glob.sync(`${dir}/**/*.{ts,tsx,js,jsx}`);
> 
> export default defineConfig({
>   resolve: {
>     alias: {
>       '@root': rootDir,
>       '@src': srcDir,
>       '@assets': assetsDir,
>       '@pages': pagesDir,
>       '@modules': modulesDir,
>     },
>   },
>   plugins: [
>     makeManifest({
>       getCacheInvalidationKey,
>     }),
>     react(),
>     customDynamicImport(),
>     addHmr({ background: enableHmrInBackgroundScript, view: true }),
>     isDev && watchRebuild({ afterWriteBundle: regenerateCacheInvalidationKey }),
>   ],
>   publicDir,
>   build: {
>     outDir,
>     sourcemap: isDev,
>     minify: isProduction,
>     modulePreload: false,
>     reportCompressedSize: isProduction,
>     emptyOutDir: !isDev,
>     rollupOptions: {
>       input: {
>         devtools: resolve(pagesDir, 'devtools', 'index.html'),
>         panel: resolve(pagesDir, 'panel', 'index.html'),
>         content: resolve(pagesDir, 'content', 'index.ts'),
>         background: resolve(pagesDir, 'background', 'index.ts'),
>         contentStyle: resolve(pagesDir, 'content', 'style.scss'),
>         popup: resolve(pagesDir, 'popup', 'index.html'),
>         newtab: resolve(pagesDir, 'newtab', 'index.html'),
>         options: resolve(pagesDir, 'options', 'index.html'),
>         sidepanel: resolve(pagesDir, 'sidepanel', 'index.html'),
>         // Add all files from modules, utils, and components as entries
>         ...getFiles(resolve(srcDir, 'modules')).reduce((acc, file) => {
>           acc[file.replace(srcDir, '').replace(/\.[^/.]+$/, "")] = file;
>           return acc;
>         }, {}),
>         ...getFiles(resolve(srcDir, 'utils')).reduce((acc, file) => {
>           acc[file.replace(srcDir, '').replace(/\.[^/.]+$/, "")] = file;
>           return acc;
>         }, {}),
>         ...getFiles(resolve(srcDir, 'components')).reduce((acc, file) => {
>           acc[file.replace(srcDir, '').replace(/\.[^/.]+$/, "")] = file;
>           return acc;
>         }, {}),
>       },
>       output: {
>         entryFileNames: ((chunkInfo) => {
>           const { facadeModuleId } = chunkInfo;
>           const root = rootDir.replace(/\\/g, '/');
>           if (
>             facadeModuleId.includes('src/modules') ||
>             facadeModuleId.includes('src/utils') ||
>             facadeModuleId.includes('src/components')
>           ) {
>             const path = facadeModuleId.replace(`${root}/`, '').replace('.ts', '.js');
>             return `${path}`;
>           } else if (facadeModuleId.includes('src/pages')) {
>             return 'src/pages/[name]/index.js';
>           } else if (facadeModuleId.includes('node_modules')) {
>             return 'node_modules/[name]/index.js';
>           }
>           return '[name].js';
>         }) as any,
>         chunkFileNames: isDev ? 'assets/js/[name].js' : 'assets/js/[name].[hash].js',
>         assetFileNames: assetInfo => {
>           const { name } = path.parse(assetInfo.name);
>           const assetFileName = name === 'contentStyle' ? `${name}${getCacheInvalidationKey()}` : name;
>           return `assets/[ext]/${assetFileName}.chunk.[ext]`;
>         },
>       },
>     },
>   },
>   test: {
>     globals: true,
>     environment: 'jsdom',
>     include: ['**/*.test.ts', '**/*.test.tsx'],
>     setupFiles: './test-utils/vitest.setup.js',
>   },
> });
> ```
> 
> 1. **Ensure Source Maps in `tsconfig.json`**:
>    ```json
>    {
>      "compilerOptions": {
>        "sourceMap": true,
>        ...
>      }
>    }
>    ```
> 
> 2. **Start the Development Server**:
>    Make sure your development server is running: `npm run dev`.
> 
> 3. **Debug in VSCode**:
>    Open the Debug panel in VSCode (View -> Debug or `Ctrl+Shift+D`), select "Launch Chrome against localhost" and start debugging!
> 
> - Place breakpoints in your source TypeScript files.
> - If breakpoints are not hitting, check the `outDir` in your Vite config and ensure it matches where the files are being output (e.g., .js & .js.map).
> - Ensure that Chrome is opening with the correct debugging flags.
> 
> I hope this helps! It was a long tedious process to get to work, but there is a light at the end of the tunnel, I assure you!
> 
> ![image](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/60167559/06bf5ab1-3c82-4871-958c-e3635b00a0b5)
> 

Are you eager to add it to our docs?
If yes, then feel free to create PR 😁
