### ISSUE TITLE
How to use react-router-dom in popup

### ISSUE THREAD

**Issue by viennv1709** [Jonghakseo/chrome-extension-boilerplate-react-vite#324]
**Describe the bug**
I can't use react router dom in popup

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Window, Linux]
 - Browser [e.g. chrome, firefox]
 - Node Version [e.g. 18.12.0]

**Additional context**

**Comment by PatrykKuniczak** [comment]
You should use hash routing:

https://www.youtube.com/watch?v=783yXE2fPPY

If you have more questions, feel free to reopen thread ;)
