### ISSUE TITLE
I got a error from husky when I commit message.

### ISSUE THREAD

**Issue by youngrove** [Jonghakseo/chrome-extension-boilerplate-react-vite#326]
**Describe the bug**
I can't commit my files.

**To Reproduce**
I staged work files.
after, I commit and I got error.
```
SyntaxError: Unexpected token '??='
    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
husky - pre-commit hook exited with code 1 (error) 
```

**Expected behavior**
Commit success

**Screenshots**
<img width="691" alt="image" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/40445771/cf4d2bee-766e-4e25-8261-8f7c74eb0036">

**Desktop (please complete the following information):**
 - OS:  mac
 - Browser : chrome
 - Node Version:  18.12.0, 18.19.0, 20.10.0

**Additional context**

**Comment by PatrykKuniczak** [comment]
@youngrove Are you trying to delete node_modules and reinstall?

**Comment by youngrove** [comment]
> @youngrove Are you trying to delete node_modules and reinstall?

yes i did

**Comment by PatrykKuniczak** [comment]
@youngrove try to run prettier and eslint standalone, and give me info, if it's work properly each one

**Comment by youngrove** [comment]
> @youngrove try to run prettier and eslint standalone, and give me info, if it's work properly each one

I installed pnpm and then run lint, prettier. and same as above error.

**Comment by youngrove** [comment]
npm run lint, npm run prettier command is Ok.
But npm run commitlint is failed. is it problem?
<img width="1184" alt="image" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/40445771/02589f31-13e0-4948-bb17-ed087918184d">

**Comment by PatrykKuniczak** [comment]
> npm run lint, npm run prettier command is Ok.
> But npm run commitlint is failed. is it problem?
> <img width="1184" alt="image" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/40445771/02589f31-13e0-4948-bb17-ed087918184d">
> 

Did you editting .husky?

It looks like sth is wrong with that files

**Comment by PatrykKuniczak** [comment]
@youngrove solved?

**Comment by aspiers** [comment]
I got this `Unexpected token '??='` error when the linter was being run with the wrong version of node (v14.17.0).  This was due to my editor having the wrong node version on `$PATH`.
