### ISSUE TITLE
There is no build dist after npm run dev

### ISSUE THREAD

**Issue by ilbrigz** [Jonghakseo/chrome-extension-boilerplate-react-vite#33]
I am unable to run this in dev mode. How is the dev mode done exactly and what does it do? There is no dist directory after npm run dev. Am I suppose to npm run build first? But it does not rebuild whenever I change the code. Sorry just starting out building chrome extensions

Edit: I tried the https://github.com/extend-chrome/ts-react-boilerplate.git and it works. It builds to dist and hrm also works.

**Comment by namnguyen191** [comment]
> I am unable to run this in dev mode. How is the dev mode done exactly and what does it do? There is no dist directory after npm run dev. Am I suppose to npm run build first? But it does not rebuild whenever I change the code. Sorry just starting out building chrome extensions
> 
> Edit: I tried the https://github.com/extend-chrome/ts-react-boilerplate.git and it works. It builds to dist and hrm also works.

Any chance that you don't have [yarn](https://yarnpkg.com/) installed? In a recent PR they change the `dev` script to use  `yarn`. If that is the case then you can either install `yarn` or change line 14 in `package.json` to this: `"dev": "npm run build:hmr && (npm run wss & nodemon)",`

**Comment by liqiuqiui** [comment]
> 

I also encountered this problem recently, how did you solve it?

**Comment by liqiuqiui** [comment]
> I am unable to run this in dev mode. How is the dev mode done exactly and what does it do? There is no dist directory after npm run dev. Am I suppose to npm run build first? But it does not rebuild whenever I change the code. Sorry just starting out building chrome extensions
> 
> Edit: I tried the https://github.com/extend-chrome/ts-react-boilerplate.git and it works. It builds to dist and hrm also works.

I also encountered this problem recently, how did you solve it?

**Comment by Jonghakseo** [comment]
Would you like to pull the latest source from the repository and try again?

As [liqiuqiui](https://github.com/liqiuqiui) said, I suspect the problem is caused by yarn not being installed. Removed yarn inside package.json and replaced it with npm run.

**Comment by liqiuqiui** [comment]
> @ilbrigz @liqiuqiui
> 
> Would you like to pull the latest source from the repository and try again?
> 
> As [namnguyen191](https://github.com/namnguyen191) said, I suspect the problem is caused by yarn not being installed. Removed yarn inside package.json and replaced it with npm run.

Yes, I am running the latest code and yarn is installed with the latest version. I find that the command line gets stuck after the wss command is executed and does not execute the nodemon command that follows. If I re-execute yarn dev at this point, it reports an error about the port being occupied, and the nodemon command continues to be executed later, and the project runs normally and generates the dist directory. I'm not sure why this is happening.

Translated with www.DeepL.com/Translator (free version)

**Comment by Don-Cryptus** [comment]
> > @ilbrigz @liqiuqiui
> > Would you like to pull the latest source from the repository and try again?
> > As [namnguyen191](https://github.com/namnguyen191) said, I suspect the problem is caused by yarn not being installed. Removed yarn inside package.json and replaced it with npm run.
> 
> Yes, I am running the latest code and yarn is installed with the latest version. I find that the command line gets stuck after the wss command is executed and does not execute the nodemon command that follows. If I re-execute yarn dev at this point, it reports an error about the port being occupied, and the nodemon command continues to be executed later, and the project runs normally and generates the dist directory. I'm not sure why this is happening.


I am expieriencing the same problem

**Comment by liqiuqiui** [comment]
> > > @ilbrigz @liqiuqiui
> > > Would you like to pull the latest source from the repository and try again?
> > > As [namnguyen191](https://github.com/namnguyen191) said, I suspect the problem is caused by yarn not being installed. Removed yarn inside package.json and replaced it with npm run.
> > 
> > 
> > Yes, I am running the latest code and yarn is installed with the latest version. I find that the command line gets stuck after the wss command is executed and does not execute the nodemon command that follows. If I re-execute yarn dev at this point, it reports an error about the port being occupied, and the nodemon command continues to be executed later, and the project runs normally and generates the dist directory. I'm not sure why this is happening.
> 
> I am experiencing the same problem

hi, bro! I have solved this problem by running "yarn build:hmr && start /b yarn wss && nodemon" instead of "yarn build:hmr && (yarn wss & nodemon)", and the reason is Windows command line does not recognize & command.

**Comment by Don-Cryptus** [comment]
> > > > @ilbrigz @liqiuqiui
> > > > Would you like to pull the latest source from the repository and try again?
> > > > As [namnguyen191](https://github.com/namnguyen191) said, I suspect the problem is caused by yarn not being installed. Removed yarn inside package.json and replaced it with npm run.
> > > 
> > > 
> > > Yes, I am running the latest code and yarn is installed with the latest version. I find that the command line gets stuck after the wss command is executed and does not execute the nodemon command that follows. If I re-execute yarn dev at this point, it reports an error about the port being occupied, and the nodemon command continues to be executed later, and the project runs normally and generates the dist directory. I'm not sure why this is happening.
> > 
> > 
> > I am experiencing the same problem
> 
> Hi, bro! I have solved this problem by running "yarn build:hmr && start /b yarn wss && nodemon" instead of "yarn build:hmr && (yarn wss & nodemon)" command, and the reason is Windows command line does not recognize & command.

Thanks it works, I used concurrently it worked aswell but this way one dependency less

**Comment by liqiuqiui** [comment]
> > > > > @ilbrigz @liqiuqiui
> > > > > Would you like to pull the latest source from the repository and try again?
> > > > > As [namnguyen191](https://github.com/namnguyen191) said, I suspect the problem is caused by yarn not being installed. Removed yarn inside package.json and replaced it with npm run.
> > > > 
> > > > 
> > > > Yes, I am running the latest code and yarn is installed with the latest version. I find that the command line gets stuck after the wss command is executed and does not execute the nodemon command that follows. If I re-execute yarn dev at this point, it reports an error about the port being occupied, and the nodemon command continues to be executed later, and the project runs normally and generates the dist directory. I'm not sure why this is happening.
> > > 
> > > 
> > > I am experiencing the same problem
> > 
> > 
> > Hi, bro! I have solved this problem by running "yarn build:hmr && start /b yarn wss && nodemon" instead of "yarn build:hmr && (yarn wss & nodemon)" command, and the reason is Windows command line does not recognize & command.
> 
> Thanks it works, I used concurrently it worked aswell but this way one dependency less

Sorry, I don't quite understand what the second sentence means

**Comment by Don-Cryptus** [comment]
> 

https://www.npmjs.com/package/concurrently

**Comment by simpleneeraj** [comment]
Not worked in dev, build working fine 😎
