### ISSUE TITLE
Typescript's autocomplete under vscode doesn't seem to work

### ISSUE THREAD

**Issue by vvrqd26** [Jonghakseo/chrome-extension-boilerplate-react-vite#332]
**Describe the bug**
In my vscode development environment, the typescript extension is installed.
But there is no auto-complete prompt in this project. Autocomplete can work in other projects.
There may be more than just typescript that cannot work, there are no prompts, no member variable autocomplete, no css autocomplete, and no path autocomplete.

**To Reproduce**
1.  Enter code in any file

**Expected behavior**
vscode will do it autocomplete.

**Screenshots**
![image](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/125276074/3fbf2a72-4c00-470a-87f7-051170922ecc)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser chrome
 - Node Version v20.10.0
 - Vscode Version v1.85.0

**Additional context**

**Comment by Jonghakseo** [comment]
I don't have any issues with autocomplete in my vscode, and there doesn't seem to be anything in this project that would affect autocomplete, so I doubt it's a problem with other settings or anything.

**Comment by PatrykKuniczak** [comment]
I'm closing this, feel free to reopen if it's necessary
