### ISSUE TITLE
use of experimental node features causes warnings

### ISSUE THREAD

**Issue by aspiers** [Jonghakseo/chrome-extension-boilerplate-react-vite#342]
**Describe the bug**

If I run `pnpm dev` on a fresh install, I see these two warnings:

```
(node:22422) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
 Manifest file copy complete: /home/adam/git/chrome-extension-boilerplate-react-vite/dist/manifest.json
built in 1260ms.
(node:22422) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
```

I believe these are caused by the following import:

https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/blob/6b61cd12eeb2fe478a6fd290b63fb6a9ef0f9ff2/manifest.js#L1

**To Reproduce**
1. `git clone https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite.git`
2. `cd chrome-extension-boilerplate-react-vite`
3. `pnpm i`
4. `pnpm dev`

**Expected behavior**
It should start up with a clean output with no warnings.

**Comment by aspiers** [comment]
I see that [node recently gained a `--disable-warning` option](https://github.com/nodejs/node/pull/50661), so this might be a good solution, although ideally we could just avoid using experimental features altogether.  Is there another way to get `manifest.js` to read `package.json` at compile time?

**Comment by wonkyDD** [comment]
@aspiers I'm in the same situation too.
