### ISSUE TITLE
How to sync web app authentication with chrome extension

### ISSUE THREAD

**Issue by zaidbren** [Jonghakseo/chrome-extension-boilerplate-react-vite#350]
Hello everyone, I have been working on a project that involves users signing up on my main web app. The web app is created using Nextjs 14 with the new app router support and I used the next-auth to make the user sign in. Now I want to sync the authentication state between my web app and the Chrome extension, so for example, the user can authenticate on the main web app and when the user clicks on the Chrome extension on a separate tab, I want to make sure that the chrome extension shows based on the authenticated routes. It should also be able to make requests to the backend.
How can I enable something like this, I tried finding tutorials online, but I have no help yet

Thank you :)

**Comment by raynirola** [comment]
Here are a few ways to achieve this:

- **Externally Connectable (I personally use this)**: 
Use the Externally Connectable feature of Chrome Extensions. By defining specific domains in your manifest file, your web app can communicate with the extension using message passing. When a user authenticates on your web app, you can send a message to the extension to update its state. This approach is secure and provides a real-time solution to keep the extension in sync.
- **Content Script with LocalStorage Listener**: 
Implement a content script that runs on your web app's domain. The script can listen for changes to localStorage or sessionStorage, where your authentication state is stored. When a change is detected, the content script can relay that information to the background script of the extension, thereby updating its state. This method relies on the authentication logic to save the auth state on localStorage.
- **WebSockets for Real-Time Sync**: 
Implement a WebSocket connection in your Chrome extension that listens to a server endpoint. Whenever the user's authentication state changes on the server side (like through your main web app), the server can push the new state to the extension. This method provides real-time synchronization and works well for applications requiring immediate state updates. Your background service worker might die, add a heartbeat subscription to keep the connection alive.

**Comment by talpx0** [comment]
> Here are a few ways to achieve this:
> 
> * **Externally Connectable (I personally use this)**:
>   Use the Externally Connectable feature of Chrome Extensions. By defining specific domains in your manifest file, your web app can communicate with the extension using message passing. When a user authenticates on your web app, you can send a message to the extension to update its state. This approach is secure and provides a real-time solution to keep the extension in sync.
> * **Content Script with LocalStorage Listener**:
>   Implement a content script that runs on your web app's domain. The script can listen for changes to localStorage or sessionStorage, where your authentication state is stored. When a change is detected, the content script can relay that information to the background script of the extension, thereby updating its state. This method relies on the authentication logic to save the auth state on localStorage.
> * **WebSockets for Real-Time Sync**:
>   Implement a WebSocket connection in your Chrome extension that listens to a server endpoint. Whenever the user's authentication state changes on the server side (like through your main web app), the server can push the new state to the extension. This method provides real-time synchronization and works well for applications requiring immediate state updates. Your background service worker might die, add a heartbeat subscription to keep the connection alive. [Chrome Docs](https://developer.chrome.com/docs/extensions/how-to/web-platform/websockets)

could you share me with yuor solution

**Comment by raynirola** [comment]
> Hi, can you share your solution , cause I try to sync the state , I found it does not work , not matter one of the extension or react logout , they can't sync the logout stsate , thank you so much

Externally connectable:

```typescript
// manifest.js

externally_connectable: {
  matches: ['*://*.yourdomain.com/*'],
  accepts_tls_channel_id: true,
}
``` 

```typescript
// service worker

chrome.runtime.onMessageExternal.addListener(async (message, sender, sendResponse) => {
  if (message.type === 'logged-in') {
    console.dir(message);
    sendResponse({ message: 'OK' });
    return true;
  }

  if (message.type === 'logged-out') {
    console.dir(message);
    sendResponse({ message: 'OK' });
    return true;
  }
});
``` 

```typescript
// Web

const user = { id: 1234, name: 'John Doe', token: 'somejwtstuff' };

export async function sendLoggedInMessageToExtension() {
  const res = await chrome.runtime.sendMessage(
    'your-extension-id',
    { type: 'logged-in', data: user },
    { includeTlsChannelId: true }
  );

  console.log(res);
}
```

**Comment by zaidbren** [comment]
@raynirola Hello, Thank you so much for sharing the code, just a question, the web part, is that had to be the inside useEffect or it could be a server endpoint in nextjs? And can all this be done without having the web app opened on a tab?

**Comment by PatrykKuniczak** [comment]
Once i see this video: https://www.youtube.com/watch?v=dXem_TaH9To&t=529s

Maybe it explain sth for you.

I think safe and easy way to do it, is grab a cookie from your main page, and on your chrome extension, send request with this cookie for backend and check if user was authenticated.

This is good also when e.g session was expiring and the cookie disappear and you can handle logging out on plugin in one time.

**Comment by zaidbren** [comment]
@PatrykKuniczak, Yes that's the approach I took, I basically saves a user with userid and session token in the database and that cookie on the frontend. Now that cookie would be received by the chrome extension on every request and it would not able to make request to the API routes :)

Thank you for answering

**Comment by PatrykKuniczak** [comment]
@zaidbren If you want to look how to do it, let's look here: https://github.com/PatrykKuniczak/YT_Notifier/tree/main/nest-app

If you have any other question, feel free to reopen this issue :)

**Comment by dinu7172** [comment]
@PatrykKuniczak hii I have just implemented the way specify like this 
"I think safe and easy way to do it, is grab a cookie from your main page, and on your chrome extension, send request with this cookie for backend and check if user was authenticated."

but I am using the next-auth for authentication and my chrome extension is coupons sharing type of that in  which whenever user is visiting store sites like the "aliexpress.com" and others. Then it has cookies  that he get from the  main website but when it sending request backend where this cookies is decrypt in nextjs by using the getTokens(req, secret) provided next-auth then it is return null because cookie request is coming from store site ie aliexpress and not from main site. how can I fix this in more secure ways

**Comment by PatrykKuniczak** [comment]
@dinu7172 As you can see here:
https://github.com/PatrykKuniczak/YT_Notifier/blob/main/nest-app/src/auth/auth.controller.ts

on `handleRedirect` i had been sending static HTML from backend which includes cookie and then when i've wanted to destroy session on `logout` i was destroying this cookie.

But in my case, i was using only Popup, if you want to use it in content-script, it should also work, but you need to do it in other way.
As you can see here:
https://github.com/PatrykKuniczak/YT_Notifier/blob/main/react-app/src/pages/popup/pages/auth/auth.page.tsx

I was opening /login path as window, and this window was a page(hosted in the same domain as backend) where i've had my auth cookie.
And this cooke was accessible via `chrome.cookie` like here:
https://github.com/PatrykKuniczak/YT_Notifier/blob/main/react-app/utils/libs/http-client/index.ts

Where i was destroying session.

You should have access to chrome.cookie(but i'm not sure you'll be able to have it in `content-script`), i don't remember precisely how it works.

If it doesn't want to work, you can do it in e.g background or popup, like me and then share that cookie across entire application with e.g `useContext` but more secure way is to share user as me.

I hope that was clear, if you would have more questions, feel free to ask, and take a closer look on my project also on frontend and backend.

Good Luck 💯

**Comment by PatrykKuniczak** [comment]
I wasn't using next-auth, i don't know how to help you in this field 
> > [@PatrykKuniczak](https://github.com/PatrykKuniczak), Yes that's the approach I took, I basically saves a user with userid and session token in the database and that cookie on the frontend. Now that cookie would be received by the chrome extension on every request and it would be able to make request to the API routes :)
> > 
> > Thank you for answering
> 
> @zaidbren but how do you make request to API routes when you are sending from the extension by default next auth is authenticated and in that there is some same-site option in which request different sent to getTokens(req, secret) it is returning the null is response but the cookies is I am sending is correct. and it works localhost. How  do you this for next-auth?
>
