### ISSUE TITLE
Styles do not get applied using Styled Components library

### ISSUE THREAD

**Issue by OwenSamuel** [Jonghakseo/chrome-extension-boilerplate-react-vite#354]
**Is your feature request related to a problem? Please describe.**
When using the styling library [Styled Components ](https://styled-components.com/) the styling does not get applied.

**Describe the solution you'd like**
Documented steps on how to get it working or a basic working example.

**Describe alternatives you've considered**
I have considered using Tailwind and might default to that if I can not find a solution.

**Comment by OwenSamuel** [comment]
> Can you provide some example?
> 
> E.g here: https://codesandbox.io/p/sandbox/react-new

Hi, I have created a repo with a basic example of a styled component. It is a content page. 

https://github.com/OwenSamuel/chrome-extension-boilerplate-react-vite

**Comment by PatrykKuniczak** [comment]
> > Can you provide some example?
> > 
> > E.g here: https://codesandbox.io/p/sandbox/react-new
> 
> Hi, I have created a repo with a basic example of a styled component. It is a content page. You can see the content is there but the styling does not get pulled through. 
> 
> https://github.com/OwenSamuel/chrome-extension-boilerplate-react-vite

Now i remeber sth, i probably have the same problem on my project, but this is not issue with template i think, but i will take a look on that, and let you know, stay tuned 😉

**Comment by Jonghakseo** [comment]
@OwenSamuel 

Consider emotion with an almost identical interface?
Here's an example built with emotion. Check it out if you like!

- https://github.com/Jonghakseo/drag-gpt-extension
- https://github.com/Jonghakseo/drag-gpt-extension/tree/main/src/pages/content/src/ContentScriptApp/emotion

**Comment by Jonghakseo** [comment]
I'm closing the issue, please reopen if necessary.
