### ISSUE TITLE
Add Mantien UI example integration

### ISSUE THREAD

**Issue by enmanuelmag** [Jonghakseo/chrome-extension-boilerplate-react-vite#367]
**Describe the bug**
I would like to work with Mantine UI library for conteint injected scripts. I know that currently there isn't a guide to do that. I was trying to replicate the integration of the Chakra steps, but like is expected doesn't work.

**To Reproduce**
1. Clone repository
2. Follow the steps on Mangien installations [here](https://mantine.dev/guides/vite/)
3. Run the project (npm run dev)
4. Load the extension.

**Expected behavior**
Able to see the compnentes with styles of Mantine library

**Screenshots**
As you can see, the button hasn't the styles of the library.
<img width="150" alt="image" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/7991036/1f9831dd-31db-455c-9884-fafc016a19dd">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser chrome
 - Node Version 20.5.1

**Additional context**
My goal is able to use styles on the content injected scripts

**Comment by tngflx** [comment]
Bro you need to figure out way to render your button inside container that is attached with shadowDOM, then inline preload the css with chrome.geturl and then wrap it with react.render function and voila u get scoped css button.

**Comment by Jonghakseo** [comment]
If you don't mind style pollution, you can remove shadow dom logic and just use that. But I think you need to prevent style pollution 😃 

So take a look at @tngflx's comment.

**Comment by PatrykKuniczak** [comment]
@enmanuelmag Does Previous answers, solve your issue?
