### ISSUE TITLE
enabling source maps results in warning from inline-vite-preload-script.ts

### ISSUE THREAD

**Issue by aspiers** [Jonghakseo/chrome-extension-boilerplate-react-vite#374]
If I enable sourcemaps:

```diff
@@ -45,7 +45,7 @@ export default defineConfig({
   build: {
     outDir,
     /** Can slow down build speed. */
-    // sourcemap: isDev,
+    sourcemap: isDev,
     minify: isProduction,
     modulePreload: false,
     reportCompressedSize: isProduction,
```

then `pnpm dev` outputs the following warning three times:

```
(replace-vite-preload-script-plugin plugin) Sourcemap is likely to be incorrect: a plugin (replace-vite-preload-script-plugin) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help 
```

Sourcemaps are a valuable part of development, so it would be great if all plugins took the appropriate action with respect to sourcemap generation.

**Comment by tngflx** [comment]
Hmm is sourcemap really necessary? Why don't you just make breakpoint on non-production code?

**Comment by aspiers** [comment]
> Hmm is sourcemap really necessary?

Yes it is.

> Why don't you just make breakpoint on non-production code?

It does not solve any of the problems which sourcemaps solve.  They are an essential developer tool used by millions of developers, so they should always work correctly.

**Comment by Jonghakseo** [comment]
@all-contributors please add @aspiers for bug
