### ISSUE TITLE
Chakra styles are not loaded on injected content script

### ISSUE THREAD

**Issue by enmanuelmag** [Jonghakseo/chrome-extension-boilerplate-react-vite#378]
**Describe the bug**
The chakra styles are not loaded for content scripts for `Popover` component. The rest of components like Input and Labels has applied the dark theme successfully, but the PopOver doesn't.

**To Reproduce**
1. Add the custom providers and modify the root.tsx for Chakra UI
2. Load the content script
3. Load a UI component: PopOver

**Expected behavior**
The PopOver, must have the colors for theme selected,in my case dark.

**Screenshots**
<img width="255" alt="image" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/7991036/b093b83d-83d5-4c92-a8eb-1d8b272af022">

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome
 - Node Version 20

**Additional context**
I attach the custom providers and code to use Chakra as metnioned in the guide:

In root.tsx
<img width="598" alt="image" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/7991036/e6e34dcb-3c23-4427-a0fc-b4ec547ae418">

Providers:
<img width="779" alt="image" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/7991036/ece1121f-e003-48ea-b8ae-67b24b90e77f">

<img width="848" alt="image" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/7991036/c685dd8d-b60d-4859-8c5c-e707e346b64e">

<img width="803" alt="image" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/7991036/47677732-c69f-4321-aa48-e30cd4f1c884">

<img width="498" alt="image" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/7991036/1b8ea170-8a61-445e-bf77-0a57f8c1b17f">

Updates:

- Specify that `PopOver` component hasn't the theme styles applied.

**Comment by Jonghakseo** [comment]
Thank you for the detailed report. I'll take a look.

**Comment by Jonghakseo** [comment]
Strangely, the bg color used by PopOver is fixed to white

For now, I think you can use the following temporarily. I'm not sure what `--popper-bg` means, I think it's probably implementation-specific.

```tsx
      <PopoverContent
        style={{
          '--popper-bg': 'black',
        }}>
```
