### ISSUE TITLE
rollup packaging speed optimization

### ISSUE THREAD

**Issue by webLiang** [Jonghakseo/chrome-extension-boilerplate-react-vite#380]
<img width="852" alt="image" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/38065991/33707275-72ba-4086-9827-046371db90e3">

    https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/379

**Comment by Jonghakseo** [comment]
#379
