### ISSUE TITLE
[Question] 각 페이지의 역할에 대해 궁금합니다! Wondering about the role of each page!

### ISSUE THREAD

**Issue by KimCookieYa** [Jonghakseo/chrome-extension-boilerplate-react-vite#386]
안녕하세요! Chrome Extension 앱을 개발하려고 찾아보다가 너무 멋진 보일러플레이트를 발견해서 써보다가 생각보다 복잡해서 질문 남깁니다! Chrome Extension 앱 개발이 처음이어서 background, content scripts, new tap, dev tools, side panels 등등 pages 내부의 각 페이지의 역할과 할 수 있는 작업 범위에 대해 모르겠더라구요.. 크롬 확장 공식 문서에서 찾아볼 수도 있겠지만, 마침 메인테이너가 한국인이셔서 이렇게 이슈로 질문남깁니다.

그리고 Near 블록체인 네트워크를 호출하는 api를 커스텀 훅으로 분리하여 Popup.ts 내에서 호출했는데 동작하지 않더라구요. 이런 백그라운드 로직은 backgound 페이지와 content script 페이지, 둘 중 어디에서 호출해야하나요? drag gpt 예제를 보면서 할까 했지만 생각보다 많이 복잡해서... 답변해주시면 정말 감사하겠습니다!

---
Hello! I was looking into developing a Chrome Extension app and found a fantastic boilerplate to try out, but it turned out to be more complicated than I expected. It's my first time developing a Chrome Extension app, so I'm not quite sure about the roles and the scope of tasks that can be performed by each page inside pages, such as background, content scripts, new tab, dev tools, side panels, etc. I know I could probably find this information in the official Chrome extension documentation, but since the maintainer happens to be Korean, I thought I'd ask here in an issue.

Also, I tried calling the Near blockchain network API through a custom hook separated in Popup.ts, but it didn't work. Should such background logic be called in the background page or the content script page? I thought about following the drag gpt example, but it seemed quite complex... I would really appreciate it if you could answer this question!

**Comment by wonkyDD** [comment]
I'm not the one of awesome main maintainers here, but I'll answer instead.
I believe other more talented  guys will provide even better answers.
Please feel free to point out if I have misunderstood anything.

---

If you're new to extension development,  
focusing on `popup`, `content_script`, and `background` early on is sufficient.

I recommend referring to the [official docs](https://developer.chrome.com/docs/extensions/get-started/tutorial/hello-world) for detailed information on their functions and roles.  
Also, checking out cool projects like drag-gpt you have mentioned can be helpful.

You can make API calls from the popup, but in my case,  
I prefer making calls from the background and retrieving responses through [messaging](https://developer.chrome.com/docs/extensions/develop/concepts/messaging)

If API calls from the popup are not working properly, 
it would be helpful if you could provide the code snippet and any logging information related to
how the calls are being made.

**Comment by KimCookieYa** [comment]
Thank you for your answer :) I tried calling in the background and it worked fine! It didn't work at first, but I turned off all the Chrome extension apps and it worked fine! I also have a question, what is dev tools used for?

**Comment by KimCookieYa** [comment]
상세한 설명 너무 감사합니다:) 말씀해주신 대로 background에서 처리하려고 구현했고, near-api-js 라이브러리 호출 시 background scripts가 호출되지 않는 문제를 해결했습니다! 알고보니 브라우저 환경에서 near-api-js 라이브러리를 사용하기 위해서는 nodejs 모듈(https, crypto 등)을 호출해야 했고, polyfill을 세팅해주어야 했습니다..

vite-plugin-node-polyfills 설치 후, `vite.config.ts`의 plugin에 추가해서 해결했습니다.

![image](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/45006957/6871155d-1a92-4819-bd36-b9f7dc0d050d)
