### ISSUE TITLE
If use "webextension-polyfill" in project. Extension has error. "Uncaught SyntaxError: Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by xiaoxinbo118** [Jonghakseo/chrome-extension-boilerplate-react-vite#39]
Steps:
1. npm install webextension-polyfill.
2. Content and background use webextension-polyfill.
3. "import" codes in the  builded soure.
4. Install the extension, "Uncaught SyntaxError: Cannot use import statement outside a module" in background.
Question:
How to use common module without "import"?

![image](https://user-images.githubusercontent.com/7566301/206646700-d378209c-4d67-413c-bd9f-5f89ea29b653.png)

![image](https://user-images.githubusercontent.com/7566301/206644091-ace8f492-27e8-4d9a-b6b5-2b11350ced08.png)

**Comment by rajatkapoor** [comment]
I also face this issue on including this in the content Script. Or for including any external package in the content script for that matter

I saw your comment regarding how that might not be possible, but is there any workaround? I have definitely seen extentions using the webextension-polyfill in the content scripts and would really appreaciate any help in using that in this template.

**Comment by Jonghakseo** [comment]
The usage of webextension-polyfill seems to be detailed in the repo below.
It's hard to pinpoint exactly what the issue is :cry: 

https://github.com/mozilla/webextension-polyfill

**Comment by caperso** [comment]
Same, as I found it here https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/74#issuecomment-1501432588

**Comment by caperso** [comment]
Solved this by adding `type: 'module'`
<img width="448" alt="image" src="https://user-images.githubusercontent.com/34877623/230871581-3ccae14c-ba8b-4c10-a857-b8320617e333.png">

**Comment by Jonghakseo** [comment]
This issue has been closed for a long time with no additional information provided. If anyone encounters the same issue, you can re-open it with your running environment and error logs attached.
