### ISSUE TITLE
has error info in devtools when contentScript import '.index.css'

### ISSUE THREAD

**Issue by JunyWuuuu91** [Jonghakseo/chrome-extension-boilerplate-react-vite#4]
<img width="934" alt="image" src="https://user-images.githubusercontent.com/33750626/163750030-1cf79331-1815-428c-9899-fedfb34bf3a3.png">

and i not found 「Devtools Pane」in chrome devtools

**Comment by Jonghakseo** [comment]
Would you like to update the source code to the main branch and try again?

**Comment by JunyWuuuu91** [comment]
> Would you like to update the source code to the main branch and try again?

thanks, and how to use react in this contentScript.js? I could build `vendor.js` by using webpack, and config this to `manifest.json`'s "content_page" filed. So how to do this by vite？

**Comment by JunyWuuuu91** [comment]
if i use `import React from 'react'` in `contentScript.js` directly，that has error info in devtools
<img width="510" alt="image" src="https://user-images.githubusercontent.com/33750626/163977546-628f49bd-c46f-4cf6-8580-56fa634d1f1d.png">

**Comment by JunyWuuuu91** [comment]
> 

fine, i solved this problem

**Comment by Jonghakseo** [comment]
@all-contributors please add @JunyWuuuu91 for code

**Comment by Jonghakseo** [comment]
@all-contributors please add @JunyWuuuu91 for code
