### ISSUE TITLE
module.css is not picking up the styles 

### ISSUE THREAD

**Issue by tymoxx** [Jonghakseo/chrome-extension-boilerplate-react-vite#40]
I can not get the CSS modules to work. Here is what I have:

`App.module.css:`

```
.test {
  color: red;
}
```

Inside `App.tsx` I have:
``` javascript
import classes from "./App.module.css";
 ...
<h1 className={classes.test}>Some text</h1>
```

In the debugger, I see the transformed className, but the color is still not applied. 
``` javascript
<h1 class="_test_11jwl_1">TEST TEXT</h1>
```

How can I configure CSS modules?

**Comment by good-guy1218** [comment]
https://github.com/abhijithvijayan/web-extension-starter/issues/80
