### ISSUE TITLE
HMR does not work on Content Scripts Change

### ISSUE THREAD

**Issue by hhimanshu** [Jonghakseo/chrome-extension-boilerplate-react-vite#404]
**Describe the bug**
The HMR does not work when working with Content Scripts. The reload of the page is required to view the changes

**To Reproduce**
Here is the PR that has changes required to setup TailwindCSS in hope to have HMR working on Content Scripts
https://github.com/hhimanshu/chrome-ext/pull/6

**Expected behavior**
As a developer, when I make changes to code, or tailwind style in Content Script, the web page should reflect the change immediately without requiring the page reload

**Screenshots**

https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/6589036/398c73f0-621d-4a2b-941e-f69666a82529

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Brave [Version 1.61.114 Chromium: 120.0.6099.199 (Official Build) (arm64)](https://brave.com/latest/)
 - Node Version:
 ```
node -v
v20.11.1
```

**Additional context**
When a change is made, there is an activity on the terminal, but the outcome does not have the change.

**Comment by Jonghakseo** [comment]
hello. Thanks for the report.

I received the code you provided in the link and ran it and found that HMR works fine.

https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/53500778/ad55cd0a-1a74-4760-9a7a-cd54eb4758d6


After run `pnpm dev`, Could you reload extension in `chrome://extensions/` tab?

<img width="418" alt="스크린샷 2024-03-02 오후 4 17 50" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/53500778/b8941beb-b6b7-498a-b37e-32c55b16108a">

**Comment by PatrykKuniczak** [comment]
That's issue with 'Brave'

This browser can't establish connection:
![image](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/64608510/ed7bdf95-0099-4f1a-9093-325713d54341)

On the first render work's well, but after fully loaded, immediately i have info about browser can't establish websocket connection and don't refreshing page, work's as you describe.

That's not issue with Twind or other styles issue, only with this connection.
