### ISSUE TITLE
Is there any way to use React Developer Tools for debugging my extension?

### ISSUE THREAD

**Issue by RobertChaw** [Jonghakseo/chrome-extension-boilerplate-react-vite#405]
I want to use React Developer tools for debugging my extension, but there are not any tutorials on the internet.

**Comment by PatrykKuniczak** [comment]
Maybe try, to open it normally in browser, serve with vite like any other SPA page :)

**Comment by Jonghakseo** [comment]
If you want to run with JSXDev, you can use `NODE_ENV=development` before your build command, like below.

```shell
"build:watch": "cross-env __DEV__=true NODE_ENV=development vite build -w --mode development",
```

**Comment by Jonghakseo** [comment]
It can be now.

https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/blob/main/pages/popup/vite.config.ts#L30-L32

**Comment by RobertChaw** [comment]
Amazing!!
