### ISSUE TITLE
`yarn dev` not creating manifest.json on first time

### ISSUE THREAD

**Issue by ShuLaPy** [Jonghakseo/chrome-extension-boilerplate-react-vite#43]
Hey,

I cloned the repo and deleted the yarn.lock file as I was facing issues while installing node_modules.

after that as per the steps I run the `yarn dev` command.
this created a `dist` folder but the manifest.json was missing.

<img width="305" alt="Screenshot 2023-01-03 at 12 35 59 AM" src="https://user-images.githubusercontent.com/30789414/210271350-bee0220e-4c7a-4f1c-a757-8c7994b8e85c.png">

and because of that, I was getting this error while installing the extension

<img width="521" alt="Screenshot 2023-01-03 at 12 37 32 AM" src="https://user-images.githubusercontent.com/30789414/210271415-32efecd6-94bd-41b4-8446-fae526e6f66e.png">

then I ran the `yarn build` command which created a manifest.json file successfully

<img width="306" alt="Screenshot 2023-01-03 at 12 37 57 AM" src="https://user-images.githubusercontent.com/30789414/210271481-a3538a64-1e14-46d5-abf0-7b559a1cdf74.png">

---
> ### Note: but on subsequent refresh, it creates the manifest.json
---

**Comment by Jonghakseo** [comment]
Hi. I just reproduced the above situation and it didn't work.

Is the procedure I checked correct?
1. Delete node_modules
2. Delete yarn.lock
3. Run yarn install
4. Run yarn dev

manifest.json was created normally into dist folder.
Could you please provide additional information to reproduce the situation?

**Comment by ShuLaPy** [comment]
Here is the video that reproduces this bug


https://user-images.githubusercontent.com/30789414/210393145-46c131b2-9cdf-41f6-a3a7-d14f2475c247.mp4

I am using MacBook Pro M2 running 13.0.1

**Comment by Jonghakseo** [comment]
@ShuLaPy 

Thank you! This was a problem that occurred when the first manifest was created only in the public folder and not in the dist.
The PR below solved the problem. Thank you for your contribution.

- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/44

**Comment by Jonghakseo** [comment]
@all-contributors please add @ShuLaPy for bug
