### ISSUE TITLE
Filename contains the word `content` will prevent import module

### ISSUE THREAD

**Issue by YanxinTang** [Jonghakseo/chrome-extension-boilerplate-react-vite#436]
**Describe the bug**

Filename contains the word `content` will prevent import module.

**To Reproduce**
1. Clone and install
2. Rename `src/pages/content/injected/toggleTheme.ts` into `src/pages/content/injected/content-foobar.ts`
3. Update import path in `src/pages/content/injected/index.ts`
4. `pnpm run dev` and install the extension
5. Check the devtool console and you can see the error

```
content-foobar.js:59 Uncaught (in promise) ReferenceError: exampleThemeStorage is not defined
```

**Expected behavior**
Add some cautions in documents that do not name file with word `content`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Window
 - Browser chrome
 - Node Version 20.9.0

**Additional context**
No other context

**Comment by PatrykKuniczak** [comment]
Now we have new version based on turborepo, and it's works perfect for me.
@YanxinTang If this still don't work properly for you, feel free to reopen :)
