### ISSUE TITLE
Page variables and plug -in variable conflict

### ISSUE THREAD

**Issue by webLiang** [Jonghakseo/chrome-extension-boilerplate-react-vite#445]
https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/444

**Comment by webLiang** [comment]
<img width="779" alt="image" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/38065991/17939e09-1c41-4d20-aa02-ee46f69081ad">

**Comment by Jonghakseo** [comment]
Thanks~!

- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/444
