### ISSUE TITLE
Is there a way to use chrome api in the react component?

### ISSUE THREAD

**Issue by ize-302** [Jonghakseo/chrome-extension-boilerplate-react-vite#45]
I am attempting to use chrome api in the components but I get error

For example, while using `chrome.bookmarks.create` I get this error:
`TypeError: Cannot read properties of undefined (reading 'create')`

I have tried globally importing chrome api by adding `/*global chrome*/` to the top of the component but its not working

**Comment by aarcangeli** [comment]
chrome.bookmarks needs the "bookmarks" permission.

Ref: https://developer.chrome.com/docs/extensions/reference/bookmarks/

**Comment by ize-302** [comment]
Thanks for the quick reply @aarcangeli but I already have that in place

**Comment by Jonghakseo** [comment]
<img width="919" alt="스크린샷 2023-01-09 오후 8 56 05" src="https://user-images.githubusercontent.com/53500778/211302585-fda42305-60b9-437c-9b68-4826c3fd799d.png">

It's most likely that you didn't reload the extension after giving the permission in the manifest.

Try reloading the extension with the button below in `chrome://extensions/`

<img width="125" alt="스크린샷 2023-01-09 오후 8 56 41" src="https://user-images.githubusercontent.com/53500778/211302690-2bff1036-babf-4f70-9ea3-d92d195bd9a9.png">

**Comment by Jonghakseo** [comment]
> Actually, not only did I reload the extension, I also removed and uploaded it again.
> 
> As a side not, the extension doesn't use popup but it is rather injected into the web page

Are you referring to scripts injected via ContentScript?

If so, contentScript has no access to `chrome.bookmark` functionality.
https://developer.chrome.com/docs/extensions/mv3/content_scripts/

Why don't you use various chrome APIs in backgroundScript and change it to only do input/output(`message api`) in contentScript?

**Comment by ize-302** [comment]
Thank you @Jonghakseo

Yes that is what I am referring to. Currently, I am injecting the <App /> component right from the ContentScript. I am also making the bookmarks call from the background.js file which works great. 

The issue is with bookmark search api which is `chrome.bookmarks.search`. I get the response but can't seem to get it into the <App /> component. Here is my snippet:

Snippet from contentScript:
![Screenshot 2023-01-09 at 19 52 30](https://user-images.githubusercontent.com/37696853/211385349-5d9dc49b-d046-43a7-96ff-a99ad3514489.png)


Snippet from background.js
![Screenshot 2023-01-09 at 19 53 07](https://user-images.githubusercontent.com/37696853/211385457-6c89b7b8-62ca-488c-8975-11fba3b4ad66.png)


The result of the search is assigned to a variable `searchresult` but I cant seem to be able to use it in <App/> component

**Comment by Jonghakseo** [comment]
@ize-302 

This is just a React problem.
Re-rendering of React components is scheduled by default with the scheduleUpdateOnFiber method via dispatchAction .

The methods that call dispatchAction are the setState or use~ hooks we use in react.

You seem to think that the data you change outside the render of react-dom cannot be retrieved from the App component because it is not something that can be detected by the App component.

As shown below, generating a message event inside the component and managing the value as a state seems to solve the problem.

happy coding 🎉 

```tsx
import { useState } from "react";

export default function App() {
  const [result, setResult] = useState();
  const sendMsg = () => {
    chrome.runtime.sendMessage("ChromeExtensionBoilerplate", (response) => {
      setResult(response);
    });
  };

  console.log(result);

  return (
    <div className="content-view" onClick={sendMsg}>
      content view
    </div>
  );
}

```

<img width="542" alt="스크린샷 2023-01-12 오후 10 03 43" src="https://user-images.githubusercontent.com/53500778/212073622-7ba6ae76-ff33-4376-9585-d8384a369069.png">

**Comment by ize-302** [comment]
@Jonghakseo 

Didn't know I could retrieve data that changed outside the render-dom this way.

This works perfectly. Thank you. You're the best 🙌🏼
