### ISSUE TITLE
0.1.2  ERROR  run failed: command  exited (1)

### ISSUE THREAD

**Issue by ggymzz** [Jonghakseo/chrome-extension-boilerplate-react-vite#456]
**Describe the bug**
18:08:57 - Starting compilation in watch mode...
@chrome-extension-boilerplate/shared:dev: 
@chrome-extension-boilerplate/hmr:build: cache miss, executing ad81c414348df793
@chrome-extension-boilerplate/dev-utils:build: cache miss, executing 5f3ab6c9256f24ad
@chrome-extension-boilerplate/shared:clean: ERROR: command finished with error: command (D:\xx\chrome-extension\chrome-extension-boilerplate-react-vite\packages\shared) D:\xxx\nodejs\pnpm.cmd run clean exited (1)
@chrome-extension-boilerplate/shared#clean: command (D:\xxx\chrome-extension\chrome-extension-boilerplate-react-vite\packages\shared) D:\Program Files\nodejs\pnpm.cmd run clean exited (1)

 Tasks:    2 successful, 6 total
Cached:    0 cached, 6 total
  Time:    5.19s 
Failed:    @chrome-extension-boilerplate/shared#clean

 ERROR  run failed: command  exited (1)

**To Reproduce**
1. git clone
2. pnpm i
3. pnpm run dev-server  and pnpm run dev

**Expected behavior**
Want to know how to run it successfully

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: [Window11]
 - Browser [chrome]
 - Node Version [v20.9.0]

**Additional context**
none

**Comment by ggymzz** [comment]
Try again, still can't run successfully~

19:12:45 - Starting compilation in watch mode...
@chrome-extension-boilerplate/shared:dev:
@chrome-extension-boilerplate/shared:clean: [Error: EPERM: operation not permitted, unlink 'D:\xxx\chrome-extension\chrome-extension-boilerplate-react-vite\packages\shared\.turbo\turbo-dev.log'] {
@chrome-extension-boilerplate/shared:clean:   errno: -4048,
@chrome-extension-boilerplate/shared:clean:   code: 'EPERM',
@chrome-extension-boilerplate/shared:clean:   syscall: 'unlink',
@chrome-extension-boilerplate/shared:clean:   path: 'D:\\xxx\\chrome-extension\\chrome-extension-boilerplate-react-vite\\packages\\shared\\.turbo\\turbo-dev.log'
@chrome-extension-boilerplate/shared:clean: }
@chrome-extension-boilerplate/shared:clean:  ELIFECYCLE  Command failed with exit code 1.
@chrome-extension-boilerplate/dev-utils:build: cache miss, executing 55cb5216b948be06
@chrome-extension-boilerplate/hmr:build: cache miss, executing 06a657e50839466e
@chrome-extension-boilerplate/shared:clean: ERROR: command finished with error: command (D:\xxx\chrome-extension\chrome-extension-boilerplate-react-vite\packages\shared) D:\xProgram Files\nodejs\pnpm.cmd run clean exited (1)
@chrome-extension-boilerplate/shared#clean: command (D:\xxx\chrome-extension\chrome-extension-boilerplate-react-vite\packages\shared) D:\Program Files\nodejs\pnpm.cmd run clean exited (1)

 Tasks:    2 successful, 6 total
Cached:    0 cached, 6 total
  Time:    4.184s
Failed:    @chrome-extension-boilerplate/shared#clean

 ERROR  run failed: command  exited (1)

**Comment by Jonghakseo** [comment]
It looks like error about permission. Could you try as adminstration?

```
[Error: EPERM: operation not permitted, unlink 'D:\xxx\chrome-extension\chrome-extension-boilerplate-react-vite\packages\shared.turbo\turbo-dev.log'
```


- https://stackoverflow.com/a/46723597

**Comment by rhythmshandlya** [comment]
Hey, I tried to run them with administrator access, still same

**Comment by rhythmshandlya** [comment]
Similar issue when I run build command:  
  
 

![](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/72724768/9aa640c6-6123-481f-a7a0-ed47a44ae47a)

**Comment by ggymzz** [comment]
> Hey, I tried to run them with administrator access, no change,
> 
> ![](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/72724768/f5c6d863-8ceb-43a4-99fa-7342e563d9c9)

Yes, the same goes for the highest system permissions

**Comment by AfeefRazick** [comment]
Following the same steps I faced the same issue

![image](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/128598897/47db4789-1e5e-4b9e-9a16-2b95e9cee040)

**Comment by Jonghakseo** [comment]
> Following the same steps I faced the same issue

Is that the same os? windows?

**Comment by AfeefRazick** [comment]
Yes it is on Windows 11

**Comment by Jonghakseo** [comment]
- https://stackoverflow.com/questions/39293636/npm-err-error-eperm-operation-not-permitted-rename

It may helpful... hmm....

The error seems to be a permissions issue. I don't have a Windows machine right now, so it's hard to reproduce. :(

**Comment by Jonghakseo** [comment]
If the answers above don't help, try changing the following entries in your turbo.json file.

```json
//
    "build": {
      "dependsOn": ["^build"],
      "outputs": ["../../dist/**", "dist/**", "build/**"]
    },
//
```

**Comment by ggymzz** [comment]
The answer came just in time

**Comment by ggymzz** [comment]
After continuous testing, it is necessary to do this in Windows11 to run normally, and those error prompts about permissions are not accurate.
1. Remove "pnpm run clean" before all build commands
2. Then run it again

**Comment by Xdy1579883916** [comment]
@ggymzz running ~~

**Comment by AfeefRazick** [comment]
Despite trying all of the above solutions, restarting all vs code instances and running as administrator, removing the clean step as mentioned above, and restarting windows, It remains the same for me.

I am not sure if this is the case for others, but I am not able to delete the .turbo folder that is created, no matter what I do from the file explorer, it is never satisfied with the permissions which i give it.

Seems like a windows problem, I guess I'll install Linux now🫠

**Comment by ggymzz** [comment]
> Despite trying all of the above solutions, restarting all vs code instances and running as administrator, removing the clean step as mentioned above, and restarting windows, It remains the same for me.
> 
> I am not sure if this is the case for others, but I am not able to delete the .turbo folder that is created, no matter what I do from the file explorer, it is never satisfied with the permissions which i give it.
> 
> Seems like a windows problem, I guess I'll install Linux now🫠

You can get rid of "pnpn run clean &&" because I think it's conflict occupied

**Comment by AfeefRazick** [comment]
Oh my, thanks so much @ggymzz and @Jonghakseo , I did remove 'pnpm run clean &&' before, but I miscalculated the sheer number of package.json's in the repo, after replacing all of them it works.

**Comment by rhythmshandlya** [comment]
Thankyou guys, this is working for me after a pull.

**Comment by akash07k** [comment]
Is it still require to run this as admin on Windows? any workaround?

**Comment by MoaMoa90** [comment]
i also got same error on windows 11
