### ISSUE TITLE
Build fail: Vite cannot load src/assets/img/logo.svg

### ISSUE THREAD

**Issue by fazofazaal** [Jonghakseo/chrome-extension-boilerplate-react-vite#46]
Steps to reproduce:

- Fork template (Create own GitHub repo from template)
- Clone repo locally
- Change package name and description
- Yarn install dependencies `yarn` or `yarn i`
- Yarn run dev `yarn dev`

Issue:

Build failed with the following error at the bottom of this console output.

```shell
yarn dev
yarn run v1.22.11
$ npm run build:hmr && (run-p wss build:watch)
npm WARN lifecycle The node binary used for scripts is /var/folders/t8/m7d61j4n0dd_vnmxhsq54jkw0000gn/T/yarn--1673178526850-0.09484755126173594/node but npm is using /opt/homebrew/Cellar/node@14/14.19.3/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> phantasm@0.0.1 build:hmr /Users/hussainfazaal/Experiments/phantasm
> rollup --config utils/reload/rollup.config.ts


utils/reload/initReloadServer.ts → utils/reload/initReloadServer.js...
created utils/reload/initReloadServer.js in 1.6s

utils/reload/injections/script.ts → utils/reload/injections/script.js...
created utils/reload/injections/script.js in 7ms

utils/reload/injections/view.ts → utils/reload/injections/view.js...
created utils/reload/injections/view.js in 6ms
$ node utils/reload/initReloadServer.js
$ __DEV__=true vite build --watch
[HRS] Server listening at ws://localhost:8081
vite v3.1.3 building for production...

watching for file changes...

build started...
transforming (22) src/pages/newtab/Newtab.tsx Manifest file copy complete: /Users/hussainfazaal/Experiments/phantasm/dist/manifest.json
✓ 23 modules transformed.
[vite:asset] Could not load /Users/hussainfazaal/Experiments/phantasm/src/assets/img/logo.svg (imported by src/pages/popup/Popup.tsx): dir.split(...).at is not a function
transforming (50) src/pages/panel/index.css
```
Can anyone help me resolve this issue?

**Comment by Jonghakseo** [comment]
Hi. @fazofazaal 
The problematic part seems to be `dir.split(...).at is not a function`.
[Array.prototype.at](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at) method has been supported since node version 16.6.

Can you tell me which version of node you are using? It's probably a node version issue.

**Comment by Jonghakseo** [comment]
If you want to address this issue without upgrading your node version, why not try using the following function instead of `.at(-1)` ?

```ts
const assetFolder = getLastElement(dir.split("/"));

function getLastElement<T>(array: ArrayLike<T>): T {
  const length = array.length;
  const lastIndex = length - 1;
  return array[lastIndex];
}
```

And I wrote it down in README.md as 16 or higher for the node version, but I modified it to say 16.6 or higher.

**Comment by fazofazaal** [comment]
Thanks for pointing it out, I had no idea I was running a far outdated version of node `14.19.3`.  I'm having some trouble using a later node version for the project using `nvm`. Will check into this and hopefully this issue will get resolved once I'm able to upgrade the node version. Thanks for the help.

**Comment by Jonghakseo** [comment]
You're welcome. happy new year. :tada:
