### ISSUE TITLE
Storage doesn't work in background script 

### ISSUE THREAD

**Issue by vanhock** [Jonghakseo/chrome-extension-boilerplate-react-vite#479]
```
import 'webextension-polyfill';
import { exampleThemeStorage } from '@chrome-extension-boilerplate/shared';

console.log('background loaded');
console.log("Edit 'apps/chrome-extension/lib/background/index.ts' and save to reload.");

exampleThemeStorage.get().then((theme) => {
  console.log('Current theme:', theme);
});
```

**To Reproduce**
1. Go to `chrome-extension/lib/background/index.ts`
2. Add import of exampleThemeStorage or another storage
3. Try to call `.get()` method.

**Expected behavior**
On the previous version of chrome-extension-boilerplate-react-vite, everything was fine in background script.

**Screenshots**
<img width="1728" alt="image" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/8645120/edba45d6-8b55-467d-8310-3820db3f35ce">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Node Version v20.11.1

**Comment by Jonghakseo** [comment]
The short solution is add define like this

`chrome-extension/vite.config.ts`
```
export default defineConfig({
//...
  build: {
    //...
  },
  define: {
    'process.env.NODE_ENV': `"production"`,
  },
});

```

**Comment by Jonghakseo** [comment]
And I am preparing a fundamental solution.

- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/480

**Comment by vanhock** [comment]
That's awesome! Thanks!
