### ISSUE TITLE
Upgrade to Vite 4 + Rollup 3

### ISSUE THREAD

**Issue by kungfoolabs** [Jonghakseo/chrome-extension-boilerplate-react-vite#48]
Hi there, 

Just started playing with this boilerplate and tried to update to vite 4. Looks like there are some configuration changes that break.

**Comment by oliveiracdz** [comment]
Related to https://github.com/vitejs/vite/pull/9485?

**Comment by pmorch** [comment]
When I tried using vite 4, I ran into this: [Vite4 build does not respect the assets path #11424](https://github.com/vitejs/vite/issues/11424)
