### ISSUE TITLE
beginner's tutorial

### ISSUE THREAD

**Issue by Azleal** [Jonghakseo/chrome-extension-boilerplate-react-vite#482]
could you please add some beginner's tutorial on how to use this template for developers like me, who is new to chrome extensions. thanks

**Comment by Azleal** [comment]
to be more specific, say that, I'm going to build an extension, in which metamask login involved. so I think i should open `newTab` to login, after that, all pages should share the login state. there's already a lib to wrap metamask login `rainbowkit`. but in a normal react app, if you wanna use rainbowkit, the `<App />` should be wrapped by a `rainbowkit provider`. but for a chrome extension using your template, i didn't find a entrypoint like in react app. so i don't quite clear where should i use this provider so that i could use the lib.

please help me with this, thanks.

**Comment by PatrykKuniczak** [comment]
@Azleal That's the problem with the lack of knowledge of 'how chrome extension works', that's not related to this template.

But nonetheless after latest big refactor, with turborepo, the complication with beggining of developing template increase.

Either I as a contributor need to spend some times to know how the turborepo work and how to continue developing.

@Jonghakseo The more specific README should be write in the near future.

I'm close this, but let's watch this tutorials to know sth about extensions overall and react with that:
https://www.youtube.com/watch?v=0-5mPIJuwJ8&list=PLBS1L3Ug2VVrTlexfI5i9OB0KpNfIjeeN
https://www.youtube.com/watch?v=rAZXWkVhCgg&list=PLBS1L3Ug2VVods9GnWbJc__STt9VnrJ9Z
