### ISSUE TITLE
How can I add some injected content scripts?

### ISSUE THREAD

**Issue by nods-permissionlabs** [Jonghakseo/chrome-extension-boilerplate-react-vite#489]
I want to inject some content codes and use the same browser context, not an extension context. Is it possible with this boilerplate?

If possible, it would be great to have a document for that. Thank you!

**Comment by Jonghakseo** [comment]
@nods-permissionlabs 

https://developer.chrome.com/docs/extensions/reference/manifest/content-scripts?hl=ko#world-timings

You can use 'world' property!

**Comment by yejunlee-29cm** [comment]
> @nods-permissionlabs 
> 
> 
> 
> https://developer.chrome.com/docs/extensions/reference/manifest/content-scripts?hl=ko#world-timings
> 
> 
> 
> You can use 'world' property!

Thank you :<
