### ISSUE TITLE
npm run build doesn't output manifest.json

### ISSUE THREAD

**Issue by hanrongliao** [Jonghakseo/chrome-extension-boilerplate-react-vite#49]
env:
node: v16.19.0
vite: 3.1.3

It will output success when I add this code in the `makeManifest` method:

```js
setTimeout(() => {
  fs.writeFileSync(
     manifestPath,
     ManifestParser.convertManifestToString(manifest)
  );
}, 3000)
```

**Comment by Jonghakseo** [comment]
I haven't been able to reproduce the issue on that node version. Could you please provide more information about your environment?

**Comment by eliyabar** [comment]
Having this as well on windows. 
reverting this change works for me.
https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/44/files

**Comment by Jonghakseo** [comment]
First, I reverted the existing changes. We'll be looking at other bugs that required that work over time.
Thanks.

**Comment by Jonghakseo** [comment]
@all-contributors please add @hanrongliao for bug
