### ISSUE TITLE
Build command isn't working after #492

### ISSUE THREAD

**Issue by PatrykKuniczak** [Jonghakseo/chrome-extension-boilerplate-react-vite#496]
**Describe the bug**
After #492 build command is stopping on windows.
Let's rollback this PR or fix it ASAP, cause now entire template is useless on the latest version.

**Screenshots**

![Zrzut ekranu 2024-06-16 164921](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/64608510/af7476a3-80a9-4843-b533-2cef869a9c15)
![Zrzut ekranu 2024-06-16 164927](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/64608510/5d8395b3-a178-4d07-982f-a973ccd3ae2c)

**Desktop (please complete the following information):**
 - OS: Window 11
 - Node Version: 20.11.1

**Comment by Jonghakseo** [comment]
Have you tried without `=` into build command? 

```json
"build-dev-server": "pnpm -F hmr build",
```

**Comment by Jonghakseo** [comment]
Well... It looks like permission error.... hmm...

**Comment by Jonghakseo** [comment]
@PatrykKuniczak 

Could you try this? 

- #497
