### ISSUE TITLE
Add I18n package

### ISSUE THREAD

**Issue by Jonghakseo** [Jonghakseo/chrome-extension-boilerplate-react-vite#500]
**Is your feature request related to a problem? Please describe.**

To increase productivity, we will add automation and utility packages related to the addition of the I18n feature.

**Describe the solution you'd like**

In the I18n package, the message folder is built for each build, and the extension is reloaded when the i18n values are changed.

**Comment by PatrykKuniczak** [comment]
It's good idea, as i said in https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/400#issuecomment-2118693225 i was tried to implement it, but this implementation isn't good enough IMO, but it's possible to do it, but then entire build/dist folder will have different structure, maybe you will find a better solution to place json with translation in one place, and all other modules can import it without grabbing it inside its own build/dist folder
