### ISSUE TITLE
Background script throws error

### ISSUE THREAD

**Issue by SoaibHaque** [Jonghakseo/chrome-extension-boilerplate-react-vite#510]
Background scripted code contains 'process' keyword.

which leads to this bug
![image](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/72245160/0966b8f9-446b-4fc0-96a0-f8f68193f231)

This is my whole `chrome-extension/lib/background/index.ts` file
![image](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/72245160/ab6e0fed-ca42-40ad-9363-019f1810793b)

I think the '@chrome-extension-boilerplate/shared' causing this issue; if yes, then what are the solutions, I put interfaces, types, and utils code in the `shared`

**Comment by PatrykKuniczak** [comment]
We're currently working on that #503 cause there's a problem with envs and this causes many problems.

**Comment by Jonghakseo** [comment]
It can be helpful for this issue

- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/511
