### ISSUE TITLE
Separate eslint and prettier into package

### ISSUE THREAD

**Issue by wonkyDD** [Jonghakseo/chrome-extension-boilerplate-react-vite#515]
Since already tsconfig and tailwindconfig are separated ,
it would be good to separate prettier and eslint into distinct packages as well.

**Comment by PatrykKuniczak** [comment]
This is good idea, feel free to open PR 🥇

**Comment by PatrykKuniczak** [comment]
Because of https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/519#issuecomment-2226812823 i closing this, if you want to find solution and implement that in the working way, feel free to reopen :)
