### ISSUE TITLE
Injecting scripts from popup for latest version

### ISSUE THREAD

**Issue by PatrykKuniczak** [Jonghakseo/chrome-extension-boilerplate-react-vite#516]
Are we want to implement injecting scripts like in #494 also for latest version, cause now we will have it only for legacy.

I think this could be good idea.

**Comment by PatrykKuniczak** [comment]
@Jonghakseo What's decision?

**Comment by Jonghakseo** [comment]
- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/560

I don't think it's that hard to implement, and once the template suggested in the issue above is created, we can add it as one of the use cases. :)

**Comment by PatrykKuniczak** [comment]
> * [Add Template Folder with Starter Projects for Advanced Development #560](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/560)
> 
> I don't think it's that hard to implement, and once the template suggested in the issue above is created, we can add it as one of the use cases. :)

You mean what i mention in the #182 to give users option to generate only that part which they want to use, with generator #524 ?

**Comment by PatrykKuniczak** [comment]
We can do it like modules, like e.g Nest have, if user want, then install next. package with e.g authentication, but for now i think it's good idea to implement it for current code base, because people which are contributing can use this, as you can see several people https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/329#issuecomment-2171666012 waiting for that in legacy, i think it's high probability somebody waiting in latest version "__"

**Comment by PatrykKuniczak** [comment]
That's no doubt this is overengineering monster, i struggling with some changes, i think for people which want to contribute now it's about to impossible xD

After turborepo update, i need to spend so much time to know what's going on.

I think overall we can create this feature, but in the near future(closer to the end of the year), we can talk about big refactor, maybe we can talk with each other on discord after #562 and refactor this monster into more familiar like mentioned above NestJS

**Comment by PatrykKuniczak** [comment]
closed #579
