### ISSUE TITLE
Lint error occurs after the dev build in `useStorage.tsx`

### ISSUE THREAD

**Issue by wonkyDD** [Jonghakseo/chrome-extension-boilerplate-react-vite#520]
**Describe the bug**

No linting errors occur when running `pnpm lint` right after cloning the git repository,
but the following errors occur after the dev build.

```bash
chrome-extension-boilerplate-react-vite/packages/shared/lib/hooks/useStorage.tsx
2:10  error  BaseStorage not found in '@chrome-extension-boilerplate/storage'  import/named
```

**To Reproduce**
1. git clone
2. pnpm dev
3. pnpm lint

**Expected behavior**
No lint errors should occur even after the dev build.

**Screenshots**

here is a vscode screenshot.

`useStorage.tsx`

<img width="666" alt="image" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/81248624/872c2e7c-1280-4db9-93dd-ae26121c79d6">

**Comment by somykoron-it** [comment]
What is the solution?
