### ISSUE TITLE
Add script to remove all node_modules across the entire workspace

### ISSUE THREAD

**Issue by wonkyDD** [Jonghakseo/chrome-extension-boilerplate-react-vite#523]
It would be great adding a script to remove node_modules across the entire workspace. For example:

```package.json
{
  "scripts": {
    "clean:node_modules": "rimraf node_modules && pnpm -r exec rimraf node_modules"
  }
}
```

**Comment by Jonghakseo** [comment]
Is there a specific use case or reason for needing this script?

**Comment by PatrykKuniczak** [comment]
> Is there a specific use case or reason for needing this script?

Maybe if you want to bump some packages or change sth with it.

For more confidence it's good to remove all node_modules and then start new build.

I'm doing it often :)
