### ISSUE TITLE
`outDir is not inside project root and will not be emptied` warning in vite

### ISSUE THREAD

**Issue by wonkyDD** [Jonghakseo/chrome-extension-boilerplate-react-vite#526]
**Describe the bug**

In each package built with vite, log shows the following warning.
Here is a case for devtools-panel package.

```markdown
(!) outDir chrome-extension-boilerplate-react-vite/devtools-panel/dist is not inside project root
and will not be emptied. Use --emptyOutDir to override.
```

Is it really the right approach to add `--emptyOutDir` to all commands involving Vite?
Given the current repository structure, it seems it might be structurally difficult to eliminate these warnings 🧐

**To Reproduce**

1. git clone
2. pnpm i && pnpm dev

**Expected behavior**

warning disappears during the build.

**Comment by Jonghakseo** [comment]
Fixed~!

- #555
