### ISSUE TITLE
Use typescript in tailwind-config package and restruct

### ISSUE THREAD

**Issue by wonkyDD** [Jonghakseo/chrome-extension-boilerplate-react-vite#527]
It would be nice using typescript in tailwind-config package either.

Plus, renaming [tailwind.config.js](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/blob/main/packages/tailwind-config/tailwind.config.js) to kind of `base.ts`
achieving more structural consistency with others like tsconfig package.

**Comment by PatrykKuniczak** [comment]
@Jonghakseo Are you tried it before?

Cause i was saw in some place .ts or .mts don't work properly 😸

**Comment by Jonghakseo** [comment]
I'm not sure how necessary the above behavior is since type inference using jsdoc is supported, so it's not a high priority at this time. :eyes:
