### ISSUE TITLE
CSS not applying in shadowDOM in content-ui

### ISSUE THREAD

**Issue by muzammil0011** [Jonghakseo/chrome-extension-boilerplate-react-vite#539]
Use the below approach in content-ui styles in shadow DOM

`const globalStyleSheet = new CSSStyleSheet();
globalStyleSheet.replaceSync(injectedStyle);

shadowRoot.adoptedStyleSheets = [globalStyleSheet];
shadowRoot.appendChild(rootIntoShadow);`

**Comment by Jonghakseo** [comment]
@muzammil0011 

Could you please provide a more detailed explanation for people who are looking at this issues and me about what difference is from the existing implementation? It seems like tailwindcss is still being applied.
