### ISSUE TITLE
FEATURE REQUEST: replace jest with vitest

### ISSUE THREAD

**Issue by capaj** [Jonghakseo/chrome-extension-boilerplate-react-vite#54]
vite is gr8 at bundling which is very useful in tests too.
I was expecting the boilerplate to be have vitest for testing. Too bad. Can you replace jest with vitest?

**Comment by Jonghakseo** [comment]
it's possible. I also have a good experience with vitest. However, jest's ecosystem is larger and already applied, so you can create a new version with vitest applied.

**Comment by Jonghakseo** [comment]
We will close this issue as there has been no additional feedback for a long time.
