### ISSUE TITLE
Integrate @types/chrome to Reduce ts-ignore Usage

### ISSUE THREAD

**Issue by Leizhenpeng** [Jonghakseo/chrome-extension-boilerplate-react-vite#541]
The code currently contains numerous instances of `eslint-disable-next-line @typescript-eslint/ban-ts-comment` and `@ts-ignore` annotations, which can be avoided by integrating `@types/chrome`. This change will enhance code quality and maintainability by adhering to TypeScript best practices.

Example of the current issue:
```typescript
import initClient from '../initClient';

function addReload() {
  const reload = () => {
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    chrome.runtime.reload();
  };

  initClient({
    // eslint-disable-next-line
    // @ts-ignore
    id: __HMR_ID,
    onUpdate: reload,
  });
}

addReload();
```

Integrating `@types/chrome` will eliminate the need for these comments, ensuring more robust and clean code.

**Comment by Jonghakseo** [comment]
@Leizhenpeng

I just set it up to receive the Chrome type through tsconfig settings without installing any packages. Thank you for your thorough review :)
