### ISSUE TITLE
Question: Expected build order for turbo

### ISSUE THREAD

**Issue by nikevp** [Jonghakseo/chrome-extension-boilerplate-react-vite#543]
I noticed that running `pnpm clean` and then `pnpm dev` results in the following error:
```
commonjs--resolver] Failed to resolve entry for package "@chrome-extension-boilerplate/storage". The package 
│ may have incorrect main/module/exports specified in its package.json.
```

Running `pnpm dev` a second time succeeds without error as the dependency now exists. Is this expected behavior or should the build be waiting on storage/ to build first?

**Comment by Jonghakseo** [comment]
Could you please check if you have addressed the issue by responding with recent PR activities?

- #537
