### ISSUE TITLE
Update ESLint to the Latest Version to Avoid Incompatibilities

### ISSUE THREAD

**Issue by Leizhenpeng** [Jonghakseo/chrome-extension-boilerplate-react-vite#561]
It is recommended to update ESLint to the latest version to prevent potential compatibility issues. 

Keeping ESLint up-to-date ensures that we have the latest features, bug fixes, and compatibility improvements.

**Comment by PatrykKuniczak** [comment]
#465 It's sadly not that easy, because other packages doesn't support version 9. max what we can do is update to 8.57.0
