### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by PatrykKuniczak** [Jonghakseo/chrome-extension-boilerplate-react-vite#562]
I think good idea could be to open a server where we're(contributors) can talk more freely with each other on 1 channel.
And on other rest devs(which are only using our template) could sending a questions, like e.g Nest have.

@Jonghakseo What do you think about my idea, are you eager to open? 🥇

**Comment by Jonghakseo** [comment]
Okay~! I'll try to make one sometime in July (before the beginning of August at the latest).

**Comment by Jonghakseo** [comment]
https://discord.gg/Nu5Rf8xr

**Comment by grolox69** [comment]
Hey @Jonghakseo, can you please update the invite? This link expired

**Comment by Jonghakseo** [comment]
> Hey @Jonghakseo, can you please update the invite? This link expired

Sure

https://discord.gg/YZRG2z6Tsg
