### ISSUE TITLE
devtools panel not work on firefox

### ISSUE THREAD

**Issue by xxs3315** [Jonghakseo/chrome-extension-boilerplate-react-vite#566]
**Describe the bug**
Dev Tools panel does not work on firefox,  but on chrome it works.

**To Reproduce**
1. pnpm dev:firefox
2. open 'about:debugging#/runtime/this-firefox'
3. Load Temporary Add-on...
4. Select - manifest.json from dist folder at root

**Weird behavior**
firefox give me a blank dev tools page.

**Screenshots**
![image](https://github.com/user-attachments/assets/26fcd2be-0ed9-479f-844d-b79beb491976)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser: firefox 128.0
 - Node Version: v20.15.1

pls help, thx very much.

**Comment by PatrykKuniczak** [comment]
We will check it, but now it's busy time :)

I will take a look ASAP, i mean this week 😆

**Comment by PatrykKuniczak** [comment]
It's freaking hard to debug, because if i comment everything, it's still doesn't be shown.
It's seems sth with configuration is wrong, but everything looks great, and from version 45 firefox supporting this feature.

I will take a next look, yesterday

**Comment by PatrykKuniczak** [comment]
@govza If you're swimming in FF env, maybe you can help us, with this? 😄

**Comment by govza** [comment]
By missing icon I can tell. 
Added commit fixing paths to existing PR #616

**Comment by PatrykKuniczak** [comment]
@govza Good job, mate ❤️
