### ISSUE TITLE
content script is not working in file:// scheme

### ISSUE THREAD

**Issue by nikoskokkalidis** [Jonghakseo/chrome-extension-boilerplate-react-vite#57]
I have create an extension with this boilerplate.
I want to run it on file:// scheme, while viewing pdf files.
Although the dynamic import in content script is not working.
Any ideas?

**Comment by Jonghakseo** [comment]
Perhaps it would be worth considering whether it's possible for content scripts to access the file system before proceeding. Have you taken a moment to explore this possibility?

**Comment by Jonghakseo** [comment]
We will close this issue as there has been no additional feedback for a long time.
