### ISSUE TITLE
 Add ZIP Packaging Command to Scaffold for Chrome Extension Development

### ISSUE THREAD

**Issue by Leizhenpeng** [Jonghakseo/chrome-extension-boilerplate-react-vite#571]
During the development of Chrome extensions, a common requirement is to upload a ZIP file of the project. 

To streamline this process, I propose adding a ZIP packaging command to our scaffolding tools. 

This command should automatically compile and package the extension into a ZIP file, ready for upload. 

This feature would significantly enhance developer productivity by automating a frequently performed task, making the build process more efficient and error-free.

**Comment by Jonghakseo** [comment]
How about github actions?

[build-zip action](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/actions/workflows/build-zip.yml)

You can download and drag the artifact to upload it to your extension dashboard.

<img width="709" alt="스크린샷 2024-07-15 오후 6 10 06" src="https://github.com/user-attachments/assets/5e3b7799-d433-466a-b311-d396aa032a42">

<img width="423" alt="스크린샷 2024-07-15 오후 6 13 02" src="https://github.com/user-attachments/assets/06eeba00-01ce-4251-8ec7-8cab7472c43b">

**Comment by Leizhenpeng** [comment]
github action is a good sugar But we can't force users to go down this path. 

After all, this needs to be pushed to the remote repository to trigger, and it often takes a long time, and the local package is actually enough for 1-2s

**Comment by Leizhenpeng** [comment]
@Jonghakseo can try this, you only need `pnpm run zip` locally 

By the way, I used to be a high github action enthusiast, but I still like the browser plug-in packaging part, especially when it comes to uploading Google Extension Market

 Remote packaging is not only slow, but also more than once network problems, leaving me speechless

**Comment by PatrykKuniczak** [comment]
@Leizhenpeng But if you want to upload sth to server somewhere, you need to have internet access.

Good idea could be create script which open browser on the [build-zip action](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/actions/workflows/build-zip.yml)

But you're right in the case where you don't want to push changes, cause you e.g testing sth which don't work on remote but working locally, then your zip script it's amazing feature, after some changes without any commit, you can create quick zip and then upload it anywhere you want 😄
