### ISSUE TITLE
Clean node_modules script is broken

### ISSUE THREAD

**Issue by PatrykKuniczak** [Jonghakseo/chrome-extension-boilerplate-react-vite#586]
![image](https://github.com/user-attachments/assets/ee22b536-cf94-4d76-ab0f-d7eff4a72c02)

**Comment by PatrykKuniczak** [comment]
> Maybe it dosen't work right now in Windows 🫠

Yeah, windows don't like this template, we had seen it before(so many times xD)

**Comment by PatrykKuniczak** [comment]
@Jonghakseo You have closed this, but PR is still open 😁

Check it 💥

**Comment by Jonghakseo** [comment]
> @Jonghakseo You have closed this, but PR is still open 😁
> 
> Check it 💥

Oh I confused:)

**Comment by Jonghakseo** [comment]
https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/620
