### ISSUE TITLE
dev run failed after the commit "feat: ignore tailwind-output css #595 (#596) (commit: e496c72)"

### ISSUE THREAD

**Issue by xxs3315** [Jonghakseo/chrome-extension-boilerplate-react-vite#600]
**Describe the bug**
now dev run failed, missed the file tailwind-output.css(in content-ui).

**To Reproduce**
1. git clone src and pnpn install
2. pnpm dev

**failed behavior**
dev run failed.

**Screenshots**
![image](https://github.com/user-attachments/assets/f7de43e4-4742-4980-9f68-47f48ede180e)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser: 126.0.6478.183（正式版本） （64 位）
 - Node Version: v20.15.1

**Comment by Jonghakseo** [comment]
For now, I have fixed the issue by reverting.
