### ISSUE TITLE
Intermittent "discovery failed: bad grpc status code: The operation was cancelled" Error

### ISSUE THREAD

**Issue by Leizhenpeng** [Jonghakseo/chrome-extension-boilerplate-react-vite#612]
![CleanShot 2024-07-27 at 18 40 09@2x](https://github.com/user-attachments/assets/3be496e5-e919-44db-9f58-c6579f8f43ff)

We are experiencing an intermittent issue where the following error occurs during the editing process: "discovery failed: bad grpc status code: The operation was cancelled."

This issue happens frequently and seems to disrupt the workflow. It is unclear what is causing the error, and further investigation is needed to identify the root cause and implement a fix.

**Comment by Leizhenpeng** [comment]
It's not continuous. Occasionally, such mistakes are reported.

**Comment by Jonghakseo** [comment]
- https://github.com/vercel/turbo/issues/8491

👀

**Comment by PatrykKuniczak** [comment]
@Jonghakseo I was thinking about to close it, but maybe it's better to leave it open, because if the users figure it, then can easly find it, because of the small amount of issues, we can avoid duplicated issues 😆

**Comment by JDaoMothership** [comment]
+1 am also receiving this error intermittently in my project.

**Comment by PatrykKuniczak** [comment]
@JDaoMothership Yeah, but as @Jonghakseo linked, that's not our extension related problem.

**Comment by JDaoMothership** [comment]
oop, apologies, I was just googling for solutions, and thought I was still in the vercel/turbo land. My bad!

**Comment by PatrykKuniczak** [comment]
@JDaoMothership Don't worry, if you're here already, you can browse our https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/blob/main/README.md 😆

**Comment by PatrykKuniczak** [comment]
I'm closing this, because we aren't able to do anything with this, and turbo doesn't matter about that ...

**Comment by dandv** [comment]
I'm also running into this issue. As long as it's not fixed, it should stay open.

**Comment by dandv** [comment]
I found a workaround: `killall turbo`.
