### ISSUE TITLE
Creating types in the packages/shared module does not generate declaration files correctly.

### ISSUE THREAD

**Issue by beanu** [Jonghakseo/chrome-extension-boilerplate-react-vite#619]
**Describe the bug**
The creation of types within the packages/shared module fails to generate declaration files accurately.

**To Reproduce**
1.  Go to 'packages/shared/lib'
2. Create folder  'types'
3. Create file 'entity.ts'
4. `export type ProcessedTweet = {
  content: string;
  date: string;
  hashtags: string;
};`

5. Create file 'types/index.ts'
6. modify 'shared/index.ts'

**Expected behavior**
The declaration files can be generated correctly in the dist, and the common types can be called in other modules. 

**Screenshots**
<img width="735" alt="image" src="https://github.com/user-attachments/assets/37164e94-4aea-4761-bc4a-193883f98b62">

**Desktop (please complete the following information):**
 - OS: [Mac]
 - Browser [chrome]
 - Node Version [18.12.0]

**Comment by Jonghakseo** [comment]
Declarations for types are exported via index.ts in package.json. Is there a problem with importing and using types without a separate declaration file?
