### ISSUE TITLE
Can I use node 20 (LTS)

### ISSUE THREAD

**Issue by ashuvssut** [Jonghakseo/chrome-extension-boilerplate-react-vite#628]
# Question

Can I use node 20 (LTS) safely or will there be any issues?

in .nvmrc, node 18 LTS is recommended

**Comment by Jonghakseo** [comment]
@ashuvssut 

Hi, I think it's best to understand that the node version written in the `.nvmrc` is the minimum node version that the project currently supports. As far as I know, there are no issues with node 20, so you should be able to use it~!
