### ISSUE TITLE
How to add Material UI

### ISSUE THREAD

**Issue by codergigachad** [Jonghakseo/chrome-extension-boilerplate-react-vite#651]
I want to make an extension for google products, so I need to add Material UI in content scripts to match the design language. So far Material UI works in popup but doesn't work inside content scripts. The component html shows on the page but the css and maybe even js doesn't work.
Maybe I need to manually build the css for material but I don't know how to do it can you please help.

An alternative to this for this repo can be [material tailwind](https://www.material-tailwind.com/). If material doesn't work, can you please tell me how to use material tailwind.

**Comment by wonkyDD** [comment]
@Jonghakseo 

It would be great to have some incentives or systems in this repo
to actively create integration guides for various UI libraries including  shadcn, daisy, next, etc...  including mui.

It might be a good idea to pin the issue or add some notices into readme as well.

I remember that quite a few issues titled somewhat of  ***how to add/integrate xxx ui?*** were opened often
even during the legacy version.

And mostly content-ui has caused it.

**Comment by PatrykKuniczak** [comment]
> @Jonghakseo 
> @PatrykKuniczak 
> 
> It would be great to have some incentives or systems in this repo
> to actively create integration guides for various UI libraries including  shadcn, daisy, next, etc...  including mui.
> 
> It might be a good idea to pin the issue or add some notices into readme as well.
> 
> I remember that quite a few issues titled somewhat of  ***how to add/integrate xxx ui?*** were opened often
> even during the legacy version.
> 
> And mostly content-ui has caused it.

You can open that issue, and list all packages which you want to integrate, and we can pin it 😁

**Comment by codergigachad** [comment]
@wonkyDD @PatrykKuniczak That's a good initiative for this project's future, but can you please tell me how to add MUI right now.

**Comment by PatrykKuniczak** [comment]
> @wonkyDD @PatrykKuniczak That's a good initiative for this project's future, but can you please tell me how to add MUI right now.

https://github.com/PatrykKuniczak/YT_Notifier/tree/main/react-app

Here i have mui with styled components, but there's legacy version, but config should be similar

**Comment by codergigachad** [comment]
@PatrykKuniczak This repository doesn't utilize any MUI component in content scripts. Can you provide me the code on how to do it.

**Comment by PatrykKuniczak** [comment]
@codergigachad OO i was missed, you want to inject in into content script.

I didn't done it never before.

I need to take a look for that, but i'm not able to do it now.

**Comment by PatrykKuniczak** [comment]
@codergigachad If you still struggling with this, feel free to visit us on [Discord](https://discord.com/invite/4ERQ6jgV9a)

**Comment by PatrykKuniczak** [comment]
If you still have problem with it, let's visit our Discord.

We have on legacy some tutorials to add several UI packages:
https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/tree/legacy?tab=readme-ov-file#add-style-library-

We need to add it in new docs
