### ISSUE TITLE
Make the boilerplate modular

### ISSUE THREAD

**Issue by lucafaggianelli** [Jonghakseo/chrome-extension-boilerplate-react-vite#673]
**Is your feature request related to a problem? Please describe.**
I love this boilerplate, though is way too much complete for me, I just need the popup and the background script, how can I disable the rest easily and possibly non deleting any file as I may need something like the side-panel in the future?

**Describe the solution you'd like**
I'd like a *boolean* configuration somewhere, for example in the manifest.js file to select only the features I need i.e.:
```js
const config = {
  popup: true,
  sidePanel: false,
}
```

I expect the items with `false` not to appear in the dist/ directory after build

**Describe alternatives you've considered**
Deleting unused folders and modifying the manifest.js itself

**Additional context**
-

**Comment by PatrykKuniczak** [comment]
@lucafaggianelli We have it in mind.

It's duplicated with my issue #182 

Maybe in this year, we will done refactor where `chrome-extension` will be a mother like `NestJS` have.
And rest modules will be installed depends on needs 😄
