### ISSUE TITLE
The project won't get up and running

### ISSUE THREAD

**Issue by Alex20180512** [Jonghakseo/chrome-extension-boilerplate-react-vite#692]
**Describe the bug**

I pulled the latest code locally, installed the dependencies and ran the project with sudo pnpm dev when it reported an error: server is unavailable: channel closed

**To Reproduce**
1. Clone it directly to your local system and run it with sudo pnpm dev after installing the dependencies.

**Expected behavior**
The project is operational

**Screenshots**

![截屏2024-09-02 13 14 01](https://github.com/user-attachments/assets/1e17199d-20b3-45c4-a1b2-394dc2adfd6a)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: chrome
 - Node Version: v20.14.0

**Comment by PatrykKuniczak** [comment]
@Alex20180512 That's sadly not our case, it's `turbo` related.

Max. you can do for now it's run `turbo daemon stop` or `pnpm clean` to clean everything.

Let my know it will helps you :)

**Comment by chrisneal** [comment]
> @Alex20180512 That's sadly not our case, it's `turbo` related.
> 
> Max. you can do for now it's run `turbo daemon stop` or `pnpm clean:turbo` to clean everything.
> 
> Let my know it will helps you :)

This didn't work for me. In the package.json file, I had to switch it from `watch` to `run`. That fixes it, and I'm not sure what I'm missing as everything seems to be working as I'd expect?

**Comment by PatrykKuniczak** [comment]
@Alex20180512 Anyway, i can change it, because it works the same for me on Windows 11

**Comment by Alex20180512** [comment]
> > > @Alex20180512 That's sadly not our case, it's `turbo` related.
> > > Max. you can do for now it's run `turbo daemon stop` or `pnpm clean:turbo` to clean everything.
> > > Let my know it will helps you :)
> > 
> > 
> > This didn't work for me. In the package.json file, I had to switch it from `watch` to `run`. That fixes it, and I'm not sure what I'm missing as everything seems to be working as I'd expect?
> > ```json
> >     "dev": "turbo ready && turbo watch dev --concurrency 20",
> >     "dev:firefox": "turbo ready && cross-env __FIREFOX__=true turbo watch dev --concurrency 20",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```json
> >     "dev": "turbo ready && turbo run dev --concurrency 20",
> >     "dev:firefox": "turbo ready && cross-env __FIREFOX__=true turbo run dev --concurrency 20",
> > ```
> 
>  你的操作系统是什么？

I'm using MacOS.

**Comment by Alex20180512** [comment]
> > @Alex20180512 That's sadly not our case, it's `turbo` related.
> > Max. you can do for now it's run `turbo daemon stop` or `pnpm clean:turbo` to clean everything.
> > Let my know it will helps you :)
> 
> 这对我不起作用。在 package.json 文件中，我不得不将其从`watch`改为`run`。这样就解决了问题，我不知道自己漏掉了什么，因为一切似乎都在按照我的预期运行？
> 
> ```json
>     "dev": "turbo ready && turbo watch dev --concurrency 20",
>     "dev:firefox": "turbo ready && cross-env __FIREFOX__=true turbo watch dev --concurrency 20",
> ```
> 
> ```json
>     "dev": "turbo ready && turbo run dev --concurrency 20",
>     "dev:firefox": "turbo ready && cross-env __FIREFOX__=true turbo run dev --concurrency 20",
> ```

Wow, I changed it to run and it worked, thank you!
