### ISSUE TITLE
Content Script cannot use React

### ISSUE THREAD

**Issue by dim0147** [Jonghakseo/chrome-extension-boilerplate-react-vite#7]
- Hi, I have the content script that will create a `div` element and use React render to that `div` then append it into the `document.body`, but  when content script loaded it show this error `Cannot use import statement outside a module`
![image](https://user-images.githubusercontent.com/44487221/174418364-e68d66bb-8378-4bb8-978d-0f8e069d0d28.png)
- My content script code:
![image](https://user-images.githubusercontent.com/44487221/174418400-bfbc9d55-9c90-4881-b7a8-889b7a6d3f86.png)

![image](https://user-images.githubusercontent.com/44487221/174418414-136547f2-7987-4b98-853d-e6ee9f89561e.png)

**Comment by Jonghakseo** [comment]
hello @dim0147  

I created a pull request to fix the issue.
- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/9

Please check if it helps you solve your problem.

Thanks for raising a useful issue.

<img src="https://media2.giphy.com/media/ZfK4cXKJTTay1Ava29/giphy.gif"/>

**Comment by dim0147** [comment]
Thank you

**Comment by Jonghakseo** [comment]
@all-contributors please add @dim0147 for bug

**Comment by Jonghakseo** [comment]
@all-contributors please add @dim0147 for bug

**Comment by Jonghakseo** [comment]
@all-contributors please add @dim0147 for bug
