### ISSUE TITLE
Getting MODULE NOT FOUND error when running `pnpm dev`

### ISSUE THREAD

**Issue by zeckdude** [Jonghakseo/chrome-extension-boilerplate-react-vite#729]
**Describe the bug**
After adding the dependencies and then running `pnpm dev`, it tries to build it but it gives me this error:

```
ro
│ llup/dist/native.js:68:76)
│       at Module._compile (node:internal/modules/cjs/loader:1376:14)
│       at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
│       at Module.load (node:internal/modules/cjs/loader:1207:32)
│       at Module._load (node:internal/modules/cjs/loader:1023:12) {
│     code: 'MODULE_NOT_FOUND',
│     requireStack: [
│       '/Users/cseckler/web/link-saver-extension/node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/native.js',
│       '/Users/cseckler/web/link-saver-extension/node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/shared/parse
│ Ast.js',
│       '/Users/cseckler/web/link-saver-extension/node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/shared/rollu
│ p.js',
│       '/Users/cseckler/web/link-saver-extension/node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/bin/rollup'
│     ]
│   }
│ }
│
│ Node.js v21.1.0
│  ELIFECYCLE  Command failed with exit code 1.
│  ELIFECYCLE  Command failed with exit code 1.
```

**To Reproduce**
1. Add dependencies
2. Run `pnpm dev`
3. Look at terminal output

**Expected behavior**
I expect it to build

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Node Version v21.1.0

**Additional context**

**Comment by Jonghakseo** [comment]
Can you tell which dependency it is? Does it reproduce with a `pnpm install` after `pnpm clean`?

**Comment by PatrykKuniczak** [comment]
If you add deps, you need to run `pnpm i` :)
Let us know if it works, and pull fresh changes from `main` because we fixed some things very recently.

**Comment by zeckdude** [comment]
> pnpm clean

When I run `pnpm clean`, it gives me the following error: `sh: pnpx: command not found`

**Comment by zeckdude** [comment]
> If you add deps, you need to run `pnpm i` :) Let us know if it works, and pull fresh changes from `main` because we fixed some things very recently.

I didn't add any new dependencies. What I meant is that I ran the install command on the existing dependencies in the project.

**Comment by PatrykKuniczak** [comment]
@zeckdude are you installed pnpm?
Are you read docs? :)
https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite?tab=readme-ov-file#getting-started-

**Comment by zeckdude** [comment]
> @zeckdude are you installed pnpm? Are you read docs? 😄 https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite?tab=readme-ov-file#getting-started-

Yes it's installed. Runnin 8.6.12 of pnpm.

I'll clone the repo to try again, but I followed the steps.

**Comment by PatrykKuniczak** [comment]
@zeckdude It's pretty old.
I have 9.10.0

But should wokrs anyway, because `pnpx` works from hymm 4/5

**Comment by zeckdude** [comment]
> @zeckdude It's pretty old. I have 9.10.0
> 
> But should works anyway, because `pnpx` works from hymm version 4/5

That was the problem! Seems like it's important to have version 9 at least.
