### ISSUE TITLE
Does this boilerplate support auto update chrome plugin from outside server

### ISSUE THREAD

**Issue by xia325** [Jonghakseo/chrome-extension-boilerplate-react-vite#736]
Does this boilerplate support auto update chrome plugin from outside server

**Comment by PatrykKuniczak** [comment]
What does it mean?

**Comment by PatrykKuniczak** [comment]
I'm reading it again.

If you mean about auto updating extenstion, chrome do it automatically:
https://developer.chrome.com/docs/extensions/how-to/distribute
