### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by dellyn** [Jonghakseo/chrome-extension-boilerplate-react-vite#74]
Hello. First of all, thank you for the great boilerplate. I am getting the error message "Uncaught SyntaxError: Cannot use import statement outside a module". It is related to importing other necessary files. How can I fix it? I tried moving the imported files to resources or inside pages. But it didn't seem to be nice fix and didn't work to avoid this error. I'm wondering why this is happening because it looks like the code is in ES6? 
P.S It happens in both development and processing.
<img width="650" alt="image" src="https://user-images.githubusercontent.com/54443742/227642283-75feca69-982b-4aa9-9e02-af2c44c22f3c.png">

**Comment by Jonghakseo** [comment]
@dellyn 

Thank you for raising the issue.
Can you provide more detailed context?
We have confirmed that it works correctly in the code below.

### content/index.ts
```ts
import { foo } from "@assets/js/util";

console.log("content loaded");

/**
 * @description
 * Chrome extensions don't support modules in content scripts.
 */
import("./components/Demo");

foo();
```

**Comment by dellyn** [comment]
As I may see this issue occurs in function getPageInfo. This function located in assets/js but inside that file I have other import from src/utilsFolder/urlUtils and in this case it occurs the issue. Because when I remove other imports and import only from assets folder then everything works well. As I understand it's not allowed to import to content script from other places except assets?

<img width="497" alt="image" src="https://user-images.githubusercontent.com/54443742/227710050-ed5b552f-e69f-456d-a0b8-35e6be40df2a.png">
<img width="497" alt="image" src="https://user-images.githubusercontent.com/54443742/227710063-a015c7c1-8e46-4221-8e22-075838ef71d0.png">

**Comment by dellyn** [comment]
UPD: Now im not really sure what's the problem about. Because I just imported axios library and it fucked up. That's strange. Maybe I will try to start from the begining 
<img width="605" alt="image" src="https://user-images.githubusercontent.com/54443742/227715416-7e06fca6-8288-4b9b-bb6b-21870e863f3d.png">

**Comment by dellyn** [comment]
> @dellyn
> 
> Thank you for raising the issue. Can you provide more detailed context? We have confirmed that it works correctly in the code below.
> 
> ### content/index.ts
> ```ts
> import { foo } from "@assets/js/util";
> 
> console.log("content loaded");
> 
> /**
>  * @description
>  * Chrome extensions don't support modules in content scripts.
>  */
> import("./components/Demo");
> 
> foo();
> ```

this is my project tree 
├─ .gitignore
├─ LICENSE
├─ Readme.md
├─ config
│  └─ index.ts
├─ jest.config.js
├─ manifest.ts
├─ nodemon.json
├─ package-lock.json
├─ package.json
├─ public
│  ├─ icon-128.png
│  ├─ icon-34.png
│  └─ manifest.json
├─ src
│  ├─ assets
│  │  ├─ img
│  │  │  └─ logo.svg
│  │  ├─ js
│  │  │  ├─ requests
│  │  │  │  └─ requests.ts
│  │  │  ├─ serverUtils
│  │  │  │  ├─ errorHandler.ts
│  │  │  │  ├─ notFoundHandler.ts
│  │  │  │  ├─ serverConstants.ts
│  │  │  │  └─ urlUtils.ts
│  │  │  └─ utils
│  │  │     ├─ constants.ts
│  │  │     ├─ html-utils.ts
│  │  │     ├─ httpClient.ts
│  │  │     └─ utils.ts
│  │  └─ style
│  │     └─ theme.scss
│  ├─ global.d.ts
│  ├─ pages
│  │  ├─ ReportForm
│  │  │  ├─ ReportForm.tsx
│  │  │  └─ reportForm.css
│  │  ├─ background
│  │  │  └─ index.ts
│  │  ├─ content
│  │  │  ├─ Banner.tsx
│  │  │  ├─ components
│  │  │  │  └─ Demo
│  │  │  │     ├─ app.test.tsx
│  │  │  │     ├─ app.tsx
│  │  │  │     └─ index.tsx
│  │  │  ├─ index.ts
│  │  │  ├─ style.scss
│  │  │  └─ types.ts
│  │  ├─ devtools
│  │  │  ├─ index.html
│  │  │  └─ index.ts
│  │  ├─ newtab
│  │  │  ├─ Newtab.css
│  │  │  ├─ Newtab.scss
│  │  │  ├─ Newtab.tsx
│  │  │  ├─ index.css
│  │  │  ├─ index.html
│  │  │  └─ index.tsx
│  │  ├─ options
│  │  │  ├─ Options.css
│  │  │  ├─ Options.tsx
│  │  │  ├─ index.css
│  │  │  ├─ index.html
│  │  │  └─ index.tsx
│  │  ├─ panel
│  │  │  ├─ Panel.css
│  │  │  ├─ Panel.tsx
│  │  │  ├─ index.css
│  │  │  ├─ index.html
│  │  │  └─ index.tsx
│  │  └─ popup
│  │     ├─ Popup.css
│  │     ├─ Popup.tsx
│  │     ├─ index.css
│  │     ├─ index.html
│  │     └─ index.tsx
│  └─ vite-env.d.ts
├─ test-utils
│  └─ jest.setup.js
├─ tsconfig.json
├─ utils
│  ├─ log.ts
│  ├─ manifest-parser
│  │  └─ index.ts
│  ├─ plugins
│  │  ├─ add-hmr.ts
│  │  ├─ custom-dynamic-import.ts
│  │  └─ make-manifest.ts
│  └─ reload
│     ├─ constant.ts
│     ├─ initReloadClient.ts
│     ├─ initReloadServer.js
│     ├─ initReloadServer.ts
│     ├─ injections
│     │  ├─ script.js
│     │  ├─ script.ts
│     │  ├─ view.js
│     │  └─ view.ts
│     ├─ interpreter
│     │  ├─ index.ts
│     │  └─ types.ts
│     ├─ rollup.config.ts
│     └─ utils.ts
├─ vite.config.ts
└─ yarn.lock

**Comment by Kishore180994** [comment]
I am having the same issue on the content scripts. My content script is not loading. It is showing me the error - "Cannot use import statement outside a module".

I have "type:module" in my package.json. Normally, it should fix this issue. But it is weird, I am not able to find the root of this cause.

**Comment by Kishore180994** [comment]
I checked my "dist" folder. When we use the "type: module", all the "import" statements should be converted to "require" statements. But I see all the imports are generated as default. Can you guys suggest any fixed related to this?

This is screenshot of my generated "index.js" inside content of the dist folder.
<img width="663" alt="image" src="https://user-images.githubusercontent.com/23616209/229329169-d119f529-ca54-41c3-b94d-877d47ba27c5.png">

**Comment by Jonghakseo** [comment]
@Kishore180994 

Well... I recently created an extension that uses this boilerplate, would you like to see this repo?
https://github.com/Jonghakseo/drag-gpt-extension

**Comment by Kishore180994** [comment]
Thank you @Jonghakseo, I will take a look and will update soon.

**Comment by caperso** [comment]
The only thing I found that is when I tried to import the ts enum in a ts file, the output from the rollup would contain the `import`, which
So I think that's the root of the problem

**Comment by caperso** [comment]
Solution: https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/39#issuecomment-1501588361

**Comment by benschac** [comment]
also got bit by this

**Comment by good-guy1218** [comment]
Hello everyone.
I think you are wrong with webpack config or tsconfig.
please check this: It would be helpful for @Kishore180994 and @dellyn 
 https://github.com/good-guy1218/frontdoor-extension

**Comment by Kishore180994** [comment]
Hi @good-guy1218 @Jonghakseo 

I have resolved the issue, thank you for following up.

It was a problem in my content/index.ts, from where it refers to Demo.

I have started building my app from content/index.tsx, that's why I got the "cannot use import statement".
Later I saw the comment in that file, and I started buildng the app from the Demo, as my root, and it started working fine.

Thanks to this boilerplate, I was able to reduce my build by almost 50%.
Glad I found this template, Thank you 😊

**Comment by micallb** [comment]
@Kishore180994 Can you elaborate with your code please?

**Comment by mehimanshupatil** [comment]
i had also same problem. 
check this comment
https://github.com/JohnBra/vite-web-extension/issues/8#issuecomment-1540344341
bundling content script into single file solves problem.

**Comment by Jonghakseo** [comment]
This issue has been closed for a long time with no additional information provided. If anyone encounters the same issue, you can re-open it with your running environment and error logs attached.

**Comment by shanehoban** [comment]
I'm getting this issue when trying to use `import` in `background.js`:

```
import reloadOnUpdate from 'virtual:reload-on-update-in-background-script'
import browser from 'webextension-polyfill'
import supabase from '@src/utils/supabaseClient'

reloadOnUpdate('pages/background')

/**
 * Extension reloading is necessary because the browser automatically caches the css.
 * If you do not use the css of the content script, please delete it.
 */
reloadOnUpdate('pages/content/style.scss')

console.log('background loaded')
```

My supabase client is simply:

```
import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  'https://<my-project-id>.supabase.co',
  '<my-anon-key>',
)

export default supabase
```

Any help greatly appreciated!

**Comment by Jonghakseo** [comment]
@all-contributors please add @dellyn for bug
