### ISSUE TITLE
DevTools icon doesn't be shown on chrome

### ISSUE THREAD

**Issue by PatrykKuniczak** [Jonghakseo/chrome-extension-boilerplate-react-vite#742]
**Describe the bug**

**To Reproduce**
1. Run `pnpm build` or `pnpm dev`
2. Load extension
3. See options in devtools console

**Expected behavior**
Icon should be shown as on Firefox.

**Screenshots**
Chrome:
![image](https://github.com/user-attachments/assets/ceab07ec-8898-4792-86fb-8937290db680)

Firefox:
![image](https://github.com/user-attachments/assets/1f7cfb69-1c34-476d-8cb7-d77ec95e7884)

**Desktop (please complete the following information):**
 - OS: Window 11
 - Browser: Chrome
 - Node Version: 20.17.0

**Comment by govza** [comment]
Works on MS Edge too.

**Comment by govza** [comment]
I don't think Chrome supports icons in the devtools at all.

Pretty old issues on chromium tracker.
https://issues.chromium.org/issues?q=canonicalid:40329463

Also there no other icons on devtools panel tabs, compared to Edge for example.

Chrome
![image](https://github.com/user-attachments/assets/38b2e51a-432c-4903-a46a-bbedb0478a5d)
Edge
![image](https://github.com/user-attachments/assets/ea157263-b9db-4fab-a6e0-b6c457a60190)

**Comment by PatrykKuniczak** [comment]
@govza As you can see, react devtools have icons, hymm, maybe they set it inside text, that's probably it, because those icons are smaller than others

**Comment by govza** [comment]
Looks like, they[ do inline icon](https://github.com/harrygz889/react/blob/0ae348018d5b3a3f1ccdd92de85d9cc581b2b98d/packages/react-devtools-extensions/src/main.js#L475)

**Comment by PatrykKuniczak** [comment]
> Looks like, they[ do inline icon](https://github.com/harrygz889/react/blob/0ae348018d5b3a3f1ccdd92de85d9cc581b2b98d/packages/react-devtools-extensions/src/main.js#L475)

Yeah, that's what i've thought.
And there's a question, we want to do it or not @Jonghakseo ?

**Comment by Jonghakseo** [comment]
> > Looks like, they[ do inline icon](https://github.com/harrygz889/react/blob/0ae348018d5b3a3f1ccdd92de85d9cc581b2b98d/packages/react-devtools-extensions/src/main.js#L475)
> 
> Yeah, that's what i've though. And there's a question, we want to do it or not @Jonghakseo ?

What does that mean? Do you have any ideas to support icons in DevTools? or just implement like React DevTools?

**Comment by PatrykKuniczak** [comment]
> > > Looks like, they[ do inline icon](https://github.com/harrygz889/react/blob/0ae348018d5b3a3f1ccdd92de85d9cc581b2b98d/packages/react-devtools-extensions/src/main.js#L475)
> > 
> > 
> > Yeah, that's what i've though. And there's a question, we want to do it or not @Jonghakseo ?
> 
> What does that mean? Do you have any ideas to support icons in DevTools? or just implement like React DevTools?

Like React DevTools

**Comment by Jonghakseo** [comment]
This is not a bug, but a feature not supported by Chrome, so we'll close it.

**Comment by PatrykKuniczak** [comment]
> This is not a bug, but a feature not supported by Chrome, so we'll close it.

But we can do it inline, You don't want it?

**Comment by Jonghakseo** [comment]
Inline seems to be possible with unicode icons, so I don't think it's a bug!

**Comment by PatrykKuniczak** [comment]
> Inline seems to be possible with unicode icons, so I don't think it's a bug!

I will open PR with it in the near future ;)
