### ISSUE TITLE
Calling someStore.getSnapshot() in background on first launch causes empty cache

### ISSUE THREAD

**Issue by IzaGz** [Jonghakseo/chrome-extension-boilerplate-react-vite#783]
When i am in background, and this the first launch, there were no `useStorage` funciton launch:
the `cache` that created inside `createStorage` is empty.
This causes an empty values going in respone for `.getSnapshot` function

**Comment by Jonghakseo** [comment]
I'll check this as soon as possible.

**Comment by Jonghakseo** [comment]
Chrome storage is asynchronously accessible, so getting the initial value with getSnapShot will inevitably return null. We recommend using the get() method to get the value asynchronously.
