### ISSUE TITLE
E2E tests for Chrome doesn't work

### ISSUE THREAD

**Issue by SebastianTroc** [Jonghakseo/chrome-extension-boilerplate-react-vite#786]
**Describe the bug**
`pnpm e2e` script crashes within the Chrome testes for all specs testing a UI rendered by the extension.
Seems that the main reason of the crashes is:
```
Error: Can't call getAttribute on element with selector "extensions-item" because element wasn't found
    at getChromeExtensionPath (/home/runner/work/chrome-extension-boilerplate/chrome-extension-boilerplate/tests/e2e/utils/extension-path.ts:9:23)
```
WebdriverIO properly opens the browser instance and perhaps installs the extension, because is appearing on the list on the opened `chrome://extensions` page. Inspecting the page source confirms that the list item is visible, but it is not achievable by the test runner.

**To Reproduce**
1. Clone repo
2. Install all dependencies according to the README.md file
3. run `pnpm e2e`

**Expected behavior**
Tests for newly cloned repo should pass.

**Screenshots**
![image](https://github.com/user-attachments/assets/62ad6281-3d7b-45e4-99eb-d1be7352ea0e)

![image](https://github.com/user-attachments/assets/a1489d7b-38eb-4e77-bce0-4f8facbe0ae0)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser WebdriverIO/chrome
 - Node Version: 18 (on Github Actions) and 22 (on desktop)

**Comment by SebastianTroc** [comment]
It is also could be quickly be reviewed by looking into github actions results of my fork:
https://github.com/SebastianTroc/chrome-extension-boilerplate/actions/runs/11957589514/job/33335102400

**Comment by Jonghakseo** [comment]
@SebastianTroc 

Thanks for the report, it looks like a bug where `webdriverio` can't access elements in shadow root.

I've modified the code to explicitly lookup into the shadow root of each element. 

Could you try applying the changes to your project after checking? Thanks!

**Comment by SebastianTroc** [comment]
Yes, I came to the same conclusions during my investigation. Perhaps the `chrome://extensions` page has changed rendering strategies and they started to use WebComponents in this view.
Nevertheless, I can't believe that I've spent half of last night trying to fix the `getChromeExtensionPath` function but without working solution... Seems like I've missed some important selector when traversing the DOM 
🤔
