### ISSUE TITLE
What is the correct way to connect the database?

### ISSUE THREAD

**Issue by kpripper** [Jonghakseo/chrome-extension-boilerplate-react-vite#789]
Greetings! What is the correct database connection option in this boilerplate? Need a server? Are the options for creating a similar boilerplate based on Next Js being considered?

**Comment by Jonghakseo** [comment]
What do you mean by “database” in this context? If you just need storage, the Chrome Extension environment provides several [storage APIs](https://developer.chrome.com/docs/extensions/reference/api/storage), including local/sessionStorage.

Connecting directly to a DB hosted on your own is generally not recommended - all of the Chrome Extension's secret keys can be easily opened externally, just like any other client-side application, which would require a separate backend server and endpoint.

**Comment by kpripper** [comment]
Thank you, comprehensively.

**Comment by kpripper** [comment]
Thank you, comprehensively.
