### ISSUE TITLE
Saving content.css does not trigger hot reload

### ISSUE THREAD

**Issue by dandv** [Jonghakseo/chrome-extension-boilerplate-react-vite#796]
Saving `chrome-extension/public/content.css` does not trigger HMR. Is that expected?

I have to manually reload the page to see the change, which wouldn't be a big problem, except that after 2-3 reloads, it stops working: I save a modified `content.css`, reload the page, but don't see obvious modifications like changing the color of a `div { border: 1px solid blue !important; }`. Code changes **are** reflected.

This makes changing the CSS a pain in the ass because I have to restart `pnpm dev` all the time.

...yet sometimes unexpectedly the modifications do reflect without restarting the dev server.

**Desktop (please complete the following information):**
 - OS: Fedora Linux
 - Browser: Chromium 125
 - Node 22.11.0

**Additional context**

I [wrote about this in the Troubleshooting section](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/794/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R196) initially, but it turns out it wasn't a rare occurrence.

**Comment by Jonghakseo** [comment]
Since updating content.css, have you tried refreshing?

By default, the HMR for Chrome extensions does not have an auto-reload feature because it only supports reloading the extension itself.
