### ISSUE TITLE
Adding the sourcemaps for development 

### ISSUE THREAD

**Issue by LironHazan** [Jonghakseo/chrome-extension-boilerplate-react-vite#8]
Hey Guys,
Thanks for a truly awesome template! I've been playing with it since Yesterday.. 🚀 
Just a minor suggestion - adding the  ```sourcemap: true``` to the [vite.config.build](https://vitejs.dev/config/#build-sourcemap) when developing is a must so worth a mention in the readme IMO.

**Comment by Jonghakseo** [comment]
@LironHazan 

Thanks for letting me know what I missed!

<img src="https://media1.giphy.com/media/2dwejHC0H3mta/giphy.gif"/>

- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/10

**Comment by Jonghakseo** [comment]
@all-contributors please add @LironHazan for enhance

**Comment by Jonghakseo** [comment]
@all-contributors please add @LironHazan for ideas
