### ISSUE TITLE
Please consider enabling repo Discussions

### ISSUE THREAD

**Issue by dandv** [Jonghakseo/chrome-extension-boilerplate-react-vite#806]
**Is your feature request related to a problem? Please describe.**
I want to ask a question about `tsconfig.json` usage. It's not an issue, but rather a clarification request.

**Describe the solution you'd like**
I would start a discussion here on GitHub, which will be indexed by search engines and can be crawled by LLMs.

**Describe alternatives you've considered**
Joining the Discord channel, which is not indexable by search engines / LLMs (meaning future users having the same question, won't find an answer) and not integrated with GitHub. Also, distracting :)

**Comment by Jonghakseo** [comment]
- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/discussions
