### ISSUE TITLE
When side-panel package is removed, make manifest giving error

### ISSUE THREAD

**Issue by akhtersoyeb** [Jonghakseo/chrome-extension-boilerplate-react-vite#807]
**To Reproduce**
1. Delete `side-panel` folder under pages
2. Comment out side panel related code from manifest.js
3. When ```pnpm run dev ``` is showing error: 
![image](https://github.com/user-attachments/assets/b7743750-8eac-4318-9bae-9e50d1d26e94)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Node Version : 20.9.0

**Comment by dandv** [comment]
Would be nice to be document how to remove unnecessary components of the extension, because out of the box (no custom code), it's over 800KB zipped. Fortunately that is downloaded only once :)

**Comment by Jonghakseo** [comment]
I looked into it and realized that the bug was caused by `deepMerge`'s argument being removed. I'll merge a fix PR!
