### ISSUE TITLE
contentStyle CSS not in the build

### ISSUE THREAD

**Issue by hugoobauer** [Jonghakseo/chrome-extension-boilerplate-react-vite#81]
How to reproduce : clone the project, yarn + yarn dev, load in Chrome -> Unable to load the `contentStyle16801943738.chunk.css` file.
It's not present in the css dir in the dist.
<img width="225" alt="image" src="https://user-images.githubusercontent.com/46481101/228905968-320a03a8-5a63-49f8-b86c-2b5550997da5.png">

With a previous version of the boilerplate on the main branch (March 8) it's working.

**Comment by Jonghakseo** [comment]
@hugoobauer 

- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/82

I'm sorry. We inadvertently merged the above dependency update PR and it caused a problem. It shouldn't happen now. We apologize for the inconvenience.

**Comment by Jonghakseo** [comment]
@all-contributors please add @hugoobauer for bug
