### ISSUE TITLE
how to remove console logs when i run pnpm build or pnpm zip?

### ISSUE THREAD

**Issue by MoaMoa90** [Jonghakseo/chrome-extension-boilerplate-react-vite#818]
for the production build, how do i remove all the console logs for dist or zip?

shoud i go with vite plugin remove console module? just like in the screenshot?

![image](https://github.com/user-attachments/assets/5f95c3c4-1401-49d1-9902-645e896c2b93)

**Comment by PatrykKuniczak** [comment]
This is not related to our project, if you want help with your specific case, you can try to request for help on our [Discord](https://discord.gg/pMm5MPax)
