### ISSUE TITLE
Multiple CSS modules for content script

### ISSUE THREAD

**Issue by hugoobauer** [Jonghakseo/chrome-extension-boilerplate-react-vite#83]
Is it possible to have multiple CSS modules for content script ?
On this [issue](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/40), the solution is to add them manually to the manifest but I'm looking a way to make it dynamic. Is it possible ?
Thanks for the help

**Comment by Jonghakseo** [comment]
Although it is possible to create dynamically, we currently do not have plans to support it. However, I believe it can be easily implemented by customizing some codes such as vite config.

**Comment by Jonghakseo** [comment]
We will close this issue as there has been no additional feedback for a long time.
