### ISSUE TITLE
styles not working?

### ISSUE THREAD

**Issue by tonychandesign** [Jonghakseo/chrome-extension-boilerplate-react-vite#93]
hello,

I can't seem to get the styles to work in the content script...  Haven't really done much outside the boilerplate

the pages/content/style.scss
```
@import "@assets/style/theme.scss";
.content-view {
  font-size: 30px;
}
.clip-button {
  background: black;
  border-radius: 5px;
  width: 30px;
  height: 10px;
  position: absolute;
  z-index: 99;
}
```

the app: pages/content/components/Demo/app.tsx

```
import "../../style.scss";
...
return (
    <div
      className="clip-button"
      style={{
        top: pos.y,
        left: pos.x,
      }}
    />
  );
```

I had originally tried to have a separate style sheet within the Demo directory itself but that also didn't work- I saw a couple of issues here saying that there was a bit of manual work involved with the config to get extra style sheets to show up so I tried using the given style sheet and it still didn't work.  I'd like to get the default given style sheet working before trying something more custom.  I'm new to Vite but the examples online seems to just suggest you can import the sheet as you would normally.

I feel like something like this should be pretty straightforward but have been stuck on it for a few hours and can't really find anything related on the stackoverflow so I'm not sure where to start.  Any help would be appreaciated!

I don't get any errors or anything... the styles just don't show up when I inspect in the browser

**Comment by Jonghakseo** [comment]
If you have written styles in the `src/pages/content/style.scss` file, you do not need to import that file in `Demo/app.tsx`.

This is what I have tried.

https://user-images.githubusercontent.com/53500778/233390017-acab6479-1480-4bbe-8729-eccabe4ac15a.mov

**Comment by good-guy1218** [comment]
Hello, I understood your issue but can you share me your Webpack config?
I think this is a problem from webpack. some plugins are required.

**Comment by pmorch** [comment]
This project uses vite, not webpack as far as I understand.

**Comment by imvedanshmehra** [comment]
Is there any way to load custom stylesheets that are placed outside of the `src/pages/content` directory?

**Comment by Jonghakseo** [comment]
@imvedanshmehra Have you tried importing in `content/style.scss`?

**Comment by thucxuong** [comment]
> 
I'll give you an example to point to `assets/style/index.css`. I'm using tailwind btw.

You will need to adjust 2 files.
1. In the vite.config.ts
`contentStyle: resolve(assetsDir, "style", "index.css"),` this will point to assets/style/index.css
`assetFileNames`, there is a logic to rename the css file. You can rename the generated css to something you desired, should contain hash key. In my case:
I've changed this
```
if (name === "contentStyle") {
  return `assets/css/contentStyle${cacheInvalidationKey}.chunk.css`;
}
```
To this
```
if (name === "styleIndex") {
  return `assets/css/styleIndex${cacheInvalidationKey}.chunk.css`;
}
```
2. You have to modify in the manifest.json file:
Change from this
```
css: ["assets/css/contentStyle<KEY>.chunk.css"],
```
to this:
```
css: ["assets/css/styleIndex<KEY>.chunk.css"],
```

**Comment by WalterZou** [comment]
> If you have written styles in the `src/pages/content/style.scss` file, you do not need to import that file in `Demo/app.tsx`.
> 
> This is what I have tried.
> 
>  2023-04-20.10.59.55.mov

 tested using your method, but the style is not taking effect
