### ISSUE TITLE
How to integrate tailwind in this boilerplate ? 

### ISSUE THREAD

**Issue by itskaransingh** [Jonghakseo/chrome-extension-boilerplate-react-vite#96]
I want to make an extension using this boilerplate I have to set up tailwindcss in this project for better dx, anyone can help me with this ?

**Comment by good-guy1218** [comment]
Hello. Please check this.
https://github.com/lxieyang/chrome-extension-boilerplate-react/issues/152

**Comment by itskaransingh** [comment]
thanks

**Comment by Jonghakseo** [comment]
@all-contributors please add @itskaransingh for ideas

**Comment by welfoz** [comment]
I've done it in this basic fork: https://github.com/selego/chrome-extension-boilerplate-react-tailwind
It is also working for html injected through the Content 🚀
